In [97]:
# import de todas las librerias que usaremos
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import seaborn as sns
pd.set_option('display.max_columns', None)
import math
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from selenium import webdriver 
from selenium.webdriver.common.keys import Keys 
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import time
from pandas import json_normalize
import requests
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.preprocessing import StandardScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [98]:
# Guardamos datos
pokemon = pd.read_csv('dataset\pokemon.csv')
pokemon_2= pd.read_csv('dataset\All_Pokemon.csv')

In [99]:
# Nos quedamos solo la 8 generacion
pokemon_2 = pokemon_2[pokemon_2["Generation"] == 8]

# Eliminamos los datos que no nos interesan y ponemos las columnas en el mismo formato para poder hacer concat
pokemon_2.drop(columns=["Mean","BMI","Mega Evolution","Alolan Form","Galarian Form","Standard Deviation","Experience type"],inplace= True)
pokemon_2.rename(columns={"Number":"pokedex_number","Att":"attack","Def":"defense","Spa":"sp_attack",
                          "Spd":"sp_defense","Spe":"speed","Experience to level 100":"experience_growth",
                          "Height":"height_m","Weight":"weight_kg","Catch Rate":"capture_rate","BST":"base_total",
                          "Type 1":"base_type","Type 2":"secondary_type","Against Fighting":"against_fight"}, inplace = True)

# Creamos columnas vacias con mismo nombre para concat
pokemon_2["base_egg_steps"] = 0
pokemon_2["base_happiness"] = 0

# Pasamos a minisculas las columnas
pokemon_2.columns = map(lambda x: str(x).lower(),pokemon_2.columns)

#Reemplazamos espacios en blancos
pokemon_2.columns=map(lambda x: str(x).replace(" ","_"),pokemon_2.columns)

# Reordenamos columnas
pokemon_2 = pokemon_2.loc[:,['pokedex_number','name','base_type', 'secondary_type','abilities', 'generation', 'legendary',
                         'attack', 'defense', 'hp', 'sp_attack', 'sp_defense', 'speed',
                         'against_bug', 'against_dark', 'against_dragon','against_electric',
                         'against_fairy', 'against_fight', 'against_fire','against_flying',
                         'against_ghost', 'against_grass', 'against_ground','against_ice', 
                         'against_normal', 'against_poison', 'against_psychic', 
                         'against_rock', 'against_steel', 'against_water', 
                         'base_egg_steps', 'base_happiness', 'base_total', 'capture_rate', 
                          'experience_growth','height_m','weight_kg'
                        ]]

# Capitalizamos las columnas
pokemon_2.columns = map(lambda x: str(x).capitalize(),pokemon_2.columns)

pokemon_2["Generation"] = pokemon_2.Generation.astype(int)
pokemon_2["Legendary"] = pokemon_2.Legendary.astype(int)

In [100]:
# Arreglamos para hacer concat con nuestro segundo dataset
pokemon.drop(columns=["japanese_name","percentage_male","classfication"], inplace=True)
# Reordenamos columnas
pokemon = pokemon.loc[:,['pokedex_number','name','type1', 'type2','abilities', 'generation', 'is_legendary',
                         'attack', 'defense', 'hp', 'sp_attack', 'sp_defense', 'speed',
                         'against_bug', 'against_dark', 'against_dragon','against_electric',
                         'against_fairy', 'against_fight', 'against_fire','against_flying',
                         'against_ghost', 'against_grass', 'against_ground','against_ice', 
                         'against_normal', 'against_poison', 'against_psychic', 
                         'against_rock', 'against_steel', 'against_water', 
                         'base_egg_steps', 'base_happiness', 'base_total', 'capture_rate', 
                          'experience_growth','height_m','weight_kg'
                        ]]

# Re nombramos algunas columnas para que sea mas claro
pokemon.rename(columns={"type1":"Base_type","type2":"Secondary_type","is_legendary":"Legendary"},inplace=True)

# Capitalizamos las columnas
pokemon.columns = map(lambda x: str(x).capitalize(),pokemon.columns)

In [101]:
# Hacemos concat de los dos Dataframes

pokemon = pd.concat([pokemon,pokemon_2])
pokemon.reset_index(drop=True)

,Pokedex_number,Name,Base_type,Secondary_type,Abilities,Generation,Legendary,Attack,Defense,Hp,Sp_attack,Sp_defense,Speed,Against_bug,Against_dark,Against_dragon,Against_electric,Against_fairy,Against_fight,Against_fire,Against_flying,Against_ghost,Against_grass,Against_ground,Against_ice,Against_normal,Against_poison,Against_psychic,Against_rock,Against_steel,Against_water,Base_egg_steps,Base_happiness,Base_total,Capture_rate,Experience_growth,Height_m,Weight_kg
0,1,Bulbasaur,grass,poison,"['Overgrow', 'Chlorophyll']",1,0,49,49,45,65,65,45,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120,70,318,45,1059860,0.7,6.9
1,2,Ivysaur,grass,poison,"['Overgrow', 'Chlorophyll']",1,0,62,63,60,80,80,60,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120,70,405,45,1059860,1.0,13.0
2,3,Venusaur,grass,poison,"['Overgrow', 'Chlorophyll']",1,0,100,123,80,122,120,80,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120,70,625,45,1059860,2.0,100.0
3,4,Charmander,fire,NaN,"['Blaze', 'Solar Power']",1,0,52,43,39,60,50,65,0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0,5120,70,309,45,1059860,0.6,8.5
4,5,Charmeleon,fire,NaN,"['Blaze', 'Solar Power']",1,0,64,58,58,80,65,80,0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0,5120,70,405,45,1059860,1.1,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911,896,Glastrier,Ice,NaN,['Chilling Neigh'],8,1,145,130,100,65,110,30,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.00,1.0,0.5,1.0,1.0,1.0,2.0,2.0,1.0,0,0,580,3,1250000,2.2,800.0
912,897,Spectrier,Ghost,NaN,['Grim Neigh'],8,1,65,60,100,145,80,130,0.5,2.0,1.0,1.0,1.0,0.0,1.0,1.0,2.0,1.00,1.0,1.0,0.0,0.5,1.0,1.0,1.0,1.0,0,0,580,3,1250000,2.0,44.5
913,898,Calyrex,Psychic,Grass,['Unnerve'],8,1,80,80,100,80,80,80,4.0,2.0,1.0,0.5,1.0,0.5,2.0,2.0,2.0,0.50,0.5,2.0,1.0,2.0,0.5,1.0,1.0,0.5,0,0,500,3,1250000,1.1,7.7
914,898,Calyrex Ice Rider,Psychic,Ice,['As One'],8,1,165,150,100,85,130,50,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.00,1.0,0.5,1.0,1.0,0.5,2.0,2.0,1.0,0,0,680,3,1250000,2.4,809.1
915,898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],8,1,85,80,100,165,100,150,1.0,4.0,1.0,1.0,1.0,0.0,1.0,1.0,4.0,1.00,1.0,1.0,0.0,0.5,0.5,1.0,1.0,1.0,0,0,680,3,1250000,2.4,53.6

In [102]:
# Scrapeamos el numero de pokedex de todos los pokemons para poder hacer merge final de los datos y stats

PATH=("C:\Program Files (x86)\chromedriver.exe")
driver=webdriver.Chrome(PATH)
driver.get("https://pokemondb.net/pokedex/all")
time.sleep(2)
p = []
name = []
hp = []
attack = []
defense= []
spa =[]
spd =[]
speed = []
bt = []
# Looping to get pokedex number + stats
for i in range(1,1216):
    
    dex = driver.find_element(By.XPATH, f'//*[@id="pokedex"]/tbody/tr[{i}]/td[1]/span').text
    p.append(dex)
    print(dex)

    nombre = driver.find_element(By.XPATH, f'//*[@id="pokedex"]/tbody/tr[{i}]/td[2]/a').text
    name.append(nombre)
    print(nombre)
    

    total = driver.find_element(By.XPATH, f'//*[@id="pokedex"]/tbody/tr[{i}]/td[4]').text
    bt.append(total)
    print(total)
    

    vida = driver.find_element(By.XPATH, f'//*[@id="pokedex"]/tbody/tr[{i}]/td[5]').text
    hp.append(vida)
    print(vida)
    

    ataque = driver.find_element(By.XPATH, f'//*[@id="pokedex"]/tbody/tr[{i}]/td[6]').text
    attack.append(ataque)
    print(ataque)
    

    defensa = driver.find_element(By.XPATH, f'//*[@id="pokedex"]/tbody/tr[{i}]/td[7]').text
    defense.append(defensa)
    print(defensa)
    

    spat = driver.find_element(By.XPATH, f'//*[@id="pokedex"]/tbody/tr[{i}]/td[8]').text
    spa.append(spat)
    print(spat)
    
    
    sped = driver.find_element(By.XPATH, f'//*[@id="pokedex"]/tbody/tr[{i}]/td[9]').text
    spd.append(sped)
    print(sped)
       
  
    velocidad = driver.find_element(By.XPATH, f'//*[@id="pokedex"]/tbody/tr[{i}]/td[10]').text
    speed.append(velocidad)
    print(velocidad)
          
driver.close()

0001
Bulbasaur
318
45
49
49
65
65
45
0002
Ivysaur
405
60
62
63
80
80
60
0003
Venusaur
525
80
82
83
100
100
80
0003
Venusaur
625
80
100
123
122
120
80
0004
Charmander
309
39
52
43
60
50
65
0005
Charmeleon
405
58
64
58
80
65
80
0006
Charizard
534
78
84
78
109
85
100
0006
Charizard
634
78
130
111
130
85
100
0006
Charizard
634
78
104
78
159
115
100
0007
Squirtle
314
44
48
65
50
64
43
0008
Wartortle
405
59
63
80
65
80
58
0009
Blastoise
530
79
83
100
85
105
78
0009
Blastoise
630
79
103
120
135
115
78
0010
Caterpie
195
45
30
35
20
20
45
0011
Metapod
205
50
20
55
25
25
30
0012
Butterfree
395
60
45
50
90
80
70
0013
Weedle
195
40
35
30
20
20
50
0014
Kakuna
205
45
25
50
25
25
35
0015
Beedrill
395
65
90
40
45
80
75
0015
Beedrill
495
65
150
40
15
80
145
0016
Pidgey
251
40
45
40
35
35
56
0017
Pidgeotto
349
63
60
55
50
50
71
0018
Pidgeot
479
83
80
75
70
70
101
0018
Pidgeot
579
83
80
80
135
80
121
0019
Rattata
253
30
56
35
25
35
72
0019
Rattata
253
30
56
35
25
35
72
0020
Raticate
413
55
81
60
50
70
97
0020
Raticate
413
75
71
70
40
80
77
0021
Spearow
262
40
60
30
31
31
70
0022
Fearow
442
65
90
65
61
61
100
0023
Ekans
288
35
60
44
40
54
55
0024
Arbok
448
60
95
69
65
79
80
0025
Pikachu
320
35
55
40
50
50
90
0025
Pikachu
430
45
80
50
75
60
120
0026
Raichu
485
60
90
55
90
80
110
0026
Raichu
485
60
85
50
95
85
110
0027
Sandshrew
300
50
75
85
20
30
40
0027
Sandshrew
300
50
75
90
10
35
40
0028
Sandslash
450
75
100
110
45
55
65
0028
Sandslash
450
75
100
120
25
65
65
0029
Nidoran♀
275
55
47
52
40
40
41
0030
Nidorina
365
70
62
67
55
55
56
0031
Nidoqueen
505
90
92
87
75
85
76
0032
Nidoran♂
273
46
57
40
40
40
50
0033
Nidorino
365
61
72
57
55
55
65
0034
Nidoking
505
81
102
77
85
75
85
0035
Clefairy
323
70
45
48
60
65
35
0036
Clefable
483
95
70
73
95
90
60
0037
Vulpix
299
38
41
40
50
65
65
0037
Vulpix
299
38
41
40
50
65
65
0038
Ninetales
505
73
76
75
81
100
100
0038
Ninetales
505
73
67
75
81
100
109
0039
Jigglypuff
270
115
45
20
45
25
20
0040
Wigglytuff
435
140
70
45
85
50
45
0041
Zubat
245
40
45
35
30
40
55
0042
Golbat
455
75
80
70
65
75
90
0043
Oddish
320
45
50
55
75
65
30
0044
Gloom
395
60
65
70
85
75
40
0045
Vileplume
490
75
80
85
110
90
50
0046
Paras
285
35
70
55
45
55
25
0047
Parasect
405
60
95
80
60
80
30
0048
Venonat
305
60
55
50
40
55
45
0049
Venomoth
450
70
65
60
90
75
90
0050
Diglett
265
10
55
25
35
45
95
0050
Diglett
265
10
55
30
35
45
90
0051
Dugtrio
425
35
100
50
50
70
120
0051
Dugtrio
425
35
100
60
50
70
110
0052
Meowth
290
40
45
35
40
40
90
0052
Meowth
290
40
35
35
50
40
90
0052
Meowth
290
50
65
55
40
40
40
0053
Persian
440
65
70
60
65
65
115
0053
Persian
440
65
60
60
75
65
115
0054
Psyduck
320
50
52
48
65
50
55
0055
Golduck
500
80
82
78
95
80
85
0056
Mankey
305
40
80
35
35
45
70
0057
Primeape
455
65
105
60
60
70
95
0058
Growlithe
350
55
70
45
70
50
60
0058
Growlithe
350
60
75
45
65
50
55
0059
Arcanine
555
90
110
80
100
80
95
0059
Arcanine
555
95
115
80
95
80
90
0060
Poliwag
300
40
50
40
40
40
90
0061
Poliwhirl
385
65
65
65
50
50
90
0062
Poliwrath
510
90
95
95
70
90
70
0063
Abra
310
25
20
15
105
55
90
0064
Kadabra
400
40
35
30
120
70
105
0065
Alakazam
500
55
50
45
135
95
120
0065
Alakazam
600
55
50
65
175
105
150
0066
Machop
305
70
80
50
35
35
35
0067
Machoke
405
80
100
70
50
60
45
0068
Machamp
505
90
130
80
65
85
55
0069
Bellsprout
300
50
75
35
70
30
40
0070
Weepinbell
390
65
90
50
85
45
55
0071
Victreebel
490
80
105
65
100
70
70
0072
Tentacool
335
40
40
35
50
100
70
0073
Tentacruel
515
80
70
65
80
120
100
0074
Geodude
300
40
80
100
30
30
20
0074
Geodude
300
40
80
100
30
30
20
0075
Graveler
390
55
95
115
45
45
35
0075
Graveler
390
55
95
115
45
45
35
0076
Golem
495
80
120
130
55
65
45
0076
Golem
495
80
120
130
55
65
45
0077
Ponyta
410
50
85
55
65
65
90
0077
Ponyta
410
50
85
55
65
65
90
0078
Rapidash
500
65
100
70
80
80
105
0078
Rapidash
500
65
100
70
80
80
105
0079
Slowpoke
315
90
65
65
40
40
15
0079
Slowpoke
315
90
65
65
40
40
15
0080
Slowbro
490
95
75
110
100
80
30
0080
Slowbro
590
95
75
180
130
80
30
0080
Slowbro
490
95
100
95
100
70
30
0081
Magnemite
325
25
35
70
95
55
45
0082
Magneton
465
50
60
95
120
70
70
0083
Farfetch'd
377
52
90
55
58
62
60
0083
Farfetch'd
377
52
95
55
58
62
55
0084
Doduo
310
35
85
45
35
35
75
0085
Dodrio
470
60
110
70
60
60
110
0086
Seel
325
65
45
55
45
70
45
0087
Dewgong
475
90
70
80
70
95
70
0088
Grimer
325
80
80
50
40
50
25
0088
Grimer
325
80
80
50
40
50
25
0089
Muk
500
105
105
75
65
100
50
0089
Muk
500
105
105
75
65
100
50
0090
Shellder
305
30
65
100
45
25
40
0091
Cloyster
525
50
95
180
85
45
70
0092
Gastly
310
30
35
30
100
35
80
0093
Haunter
405
45
50
45
115
55
95
0094
Gengar
500
60
65
60
130
75
110
0094
Gengar
600
60
65
80
170
95
130
0095
Onix
385
35
45
160
30
45
70
0096
Drowzee
328
60
48
45
43
90
42
0097
Hypno
483
85
73
70
73
115
67
0098
Krabby
325
30
105
90
25
25
50
0099
Kingler
475
55
130
115
50
50
75
0100
Voltorb
330
40
30
50
55
55
100
0100
Voltorb
330
40
30
50
55
55
100
0101
Electrode
490
60
50
70
80
80
150
0101
Electrode
490
60
50
70
80
80
150
0102
Exeggcute
325
60
40
80
60
45
40
0103
Exeggutor
530
95
95
85
125
75
55
0103
Exeggutor
530
95
105
85
125
75
45
0104
Cubone
320
50
50
95
40
50
35
0105
Marowak
425
60
80
110
50
80
45
0105
Marowak
425
60
80
110
50
80
45
0106
Hitmonlee
455
50
120
53
35
110
87
0107
Hitmonchan
455
50
105
79
35
110
76
0108
Lickitung
385
90
55
75
60
75
30
0109
Koffing
340
40
65
95
60
45
35
0110
Weezing
490
65
90
120
85
70
60
0110
Weezing
490
65
90
120
85
70
60
0111
Rhyhorn
345
80
85
95
30
30
25
0112
Rhydon
485
105
130
120
45
45
40
0113
Chansey
450
250
5
5
35
105
50
0114
Tangela
435
65
55
115
100
40
60
0115
Kangaskhan
490
105
95
80
40
80
90
0115
Kangaskhan
590
105
125
100
60
100
100
0116
Horsea
295
30
40
70
70
25
60
0117
Seadra
440
55
65
95
95
45
85
0118
Goldeen
320
45
67
60
35
50
63
0119
Seaking
450
80
92
65
65
80
68
0120
Staryu
340
30
45
55
70
55
85
0121
Starmie
520
60
75
85
100
85
115
0122
Mr. Mime
460
40
45
65
100
120
90
0122
Mr. Mime
460
50
65
65
90
90
100
0123
Scyther
500
70
110
80
55
80
105
0124
Jynx
455
65
50
35
115
95
95
0125
Electabuzz
490
65
83
57
95
85
105
0126
Magmar
495
65
95
57
100
85
93
0127
Pinsir
500
65
125
100
55
70
85
0127
Pinsir
600
65
155
120
65
90
105
0128
Tauros
490
75
100
95
40
70
110
0128
Tauros
490
75
110
105
30
70
100
0128
Tauros
490
75
110
105
30
70
100
0128
Tauros
490
75
110
105
30
70
100
0129
Magikarp
200
20
10
55
15
20
80
0130
Gyarados
540
95
125
79
60
100
81
0130
Gyarados
640
95
155
109
70
130
81
0131
Lapras
535
130
85
80
85
95
60
0132
Ditto
288
48
48
48
48
48
48
0133
Eevee
325
55
55
50
45
65
55
0133
Eevee
435
65
75
70
65
85
75
0134
Vaporeon
525
130
65
60
110
95
65
0135
Jolteon
525
65
65
60
110
95
130
0136
Flareon
525
65
130
60
95
110
65
0137
Porygon
395
65
60
70
85
75
40
0138
Omanyte
355
35
40
100
90
55
35
0139
Omastar
495
70
60
125
115
70
55
0140
Kabuto
355
30
80
90
55
45
55
0141
Kabutops
495
60
115
105
65
70
80
0142
Aerodactyl
515
80
105
65
60
75
130
0142
Aerodactyl
615
80
135
85
70
95
150
0143
Snorlax
540
160
110
65
65
110
30
0144
Articuno
580
90
85
100
95
125
85
0144
Articuno
580
90
85
85
125
100
95
0145
Zapdos
580
90
90
85
125
90
100
0145
Zapdos
580
90
125
90
85
90
100
0146
Moltres
580
90
100
90
125
85
90
0146
Moltres
580
90
85
90
100
125
90
0147
Dratini
300
41
64
45
50
50
50
0148
Dragonair
420
61
84
65
70
70
70
0149
Dragonite
600
91
134
95
100
100
80
0150
Mewtwo
680
106
110
90
154
90
130
0150
Mewtwo
780
106
190
100
154
100
130
0150
Mewtwo
780
106
150
70
194
120
140
0151
Mew
600
100
100
100
100
100
100
0152
Chikorita
318
45
49
65
49
65
45
0153
Bayleef
405
60
62
80
63
80
60
0154
Meganium
525
80
82
100
83
100
80
0155
Cyndaquil
309
39
52
43
60
50
65
0156
Quilava
405
58
64
58
80
65
80
0157
Typhlosion
534
78
84
78
109
85
100
0157
Typhlosion
534
73
84
78
119
85
95
0158
Totodile
314
50
65
64
44
48
43
0159
Croconaw
405
65
80
80
59
63
58
0160
Feraligatr
530
85
105
100
79
83
78
0161
Sentret
215
35
46
34
35
45
20
0162
Furret
415
85
76
64
45
55
90
0163
Hoothoot
262
60
30
30
36
56
50
0164
Noctowl
452
100
50
50
86
96
70
0165
Ledyba
265
40
20
30
40
80
55
0166
Ledian
390
55
35
50
55
110
85
0167
Spinarak
250
40
60
40
40
40
30
0168
Ariados
400
70
90
70
60
70
40
0169
Crobat
535
85
90
80
70
80
130
0170
Chinchou
330
75
38
38
56
56
67
0171
Lanturn
460
125
58
58
76
76
67
0172
Pichu
205
20
40
15
35
35
60
0173
Cleffa
218
50
25
28
45
55
15
0174
Igglybuff
210
90
30
15
40
20
15
0175
Togepi
245
35
20
65
40
65
20
0176
Togetic
405
55
40
85
80
105
40
0177
Natu
320
40
50
45
70
45
70
0178
Xatu
470
65
75
70
95
70
95
0179
Mareep
280
55
40
40
65
45
35
0180
Flaaffy
365
70
55
55
80
60
45
0181
Ampharos
510
90
75
85
115
90
55
0181
Ampharos
610
90
95
105
165
110
45
0182
Bellossom
490
75
80
95
90
100
50
0183
Marill
250
70
20
50
20
50
40
0184
Azumarill
420
100
50
80
60
80
50
0185
Sudowoodo
410
70
100
115
30
65
30
0186
Politoed
500
90
75
75
90
100
70
0187
Hoppip
250
35
35
40
35
55
50
0188
Skiploom
340
55
45
50
45
65
80
0189
Jumpluff
460
75
55
70
55
95
110
0190
Aipom
360
55
70
55
40
55
85
0191
Sunkern
180
30
30
30
30
30
30
0192
Sunflora
425
75
75
55
105
85
30
0193
Yanma
390
65
65
45
75
45
95
0194
Wooper
210
55
45
45
25
25
15
0194
Wooper
210
55
45
45
25
25
15
0195
Quagsire
430
95
85
85
65
65
35
0196
Espeon
525
65
65
60
130
95
110
0197
Umbreon
525
95
65
110
60
130
65
0198
Murkrow
405
60
85
42
85
42
91
0199
Slowking
490
95
75
80
100
110
30
0199
Slowking
490
95
65
80
110
110
30
0200
Misdreavus
435
60
60
60
85
85
85
0201
Unown
336
48
72
48
72
48
48
0202
Wobbuffet
405
190
33
58
33
58
33
0203
Girafarig
455
70
80
65
90
65
85
0204
Pineco
290
50
65
90
35
35
15
0205
Forretress
465
75
90
140
60
60
40
0206
Dunsparce
415
100
70
70
65
65
45
0207
Gligar
430
65
75
105
35
65
85
0208
Steelix
510
75
85
200
55
65
30
0208
Steelix
610
75
125
230
55
95
30
0209
Snubbull
300
60
80
50
40
40
30
0210
Granbull
450
90
120
75
60
60
45
0211
Qwilfish
440
65
95
85
55
55
85
0211
Qwilfish
440
65
95
85
55
55
85
0212
Scizor
500
70
130
100
55
80
65
0212
Scizor
600
70
150
140
65
100
75
0213
Shuckle
505
20
10
230
10
230
5
0214
Heracross
500
80
125
75
40
95
85
0214
Heracross
600
80
185
115
40
105
75
0215
Sneasel
430
55
95
55
35
75
115
0215
Sneasel
430
55
95
55
35
75
115
0216
Teddiursa
330
60
80
50
50
50
40
0217
Ursaring
500
90
130
75
75
75
55
0218
Slugma
250
40
40
40
70
40
20
0219
Magcargo
430
60
50
120
90
80
30
0220
Swinub
250
50
50
40
30
30
50
0221
Piloswine
450
100
100
80
60
60
50
0222
Corsola
410
65
55
95
65
95
35
0222
Corsola
410
60
55
100
65
100
30
0223
Remoraid
300
35
65
35
65
35
65
0224
Octillery
480
75
105
75
105
75
45
0225
Delibird
330
45
55
45
65
45
75
0226
Mantine
485
85
40
70
80
140
70
0227
Skarmory
465
65
80
140
40
70
70
0228
Houndour
330
45
60
30
80
50
65
0229
Houndoom
500
75
90
50
110
80
95
0229
Houndoom
600
75
90
90
140
90
115
0230
Kingdra
540
75
95
95
95
95
85
0231
Phanpy
330
90
60
60
40
40
40
0232
Donphan
500
90
120
120
60
60
50
0233
Porygon2
515
85
80
90
105
95
60
0234
Stantler
465
73
95
62
85
65
85
0235
Smeargle
250
55
20
35
20
45
75
0236
Tyrogue
210
35
35
35
35
35
35
0237
Hitmontop
455
50
95
95
35
110
70
0238
Smoochum
305
45
30
15
85
65
65
0239
Elekid
360
45
63
37
65
55
95
0240
Magby
365
45
75
37
70
55
83
0241
Miltank
490
95
80
105
40
70
100
0242
Blissey
540
255
10
10
75
135
55
0243
Raikou
580
90
85
75
115
100
115
0244
Entei
580
115
115
85
90
75
100
0245
Suicune
580
100
75
115
90
115
85
0246
Larvitar
300
50
64
50
45
50
41
0247
Pupitar
410
70
84
70
65
70
51
0248
Tyranitar
600
100
134
110
95
100
61
0248
Tyranitar
700
100
164
150
95
120
71
0249
Lugia
680
106
90
130
90
154
110
0250
Ho-oh
680
106
130
90
110
154
90
0251
Celebi
600
100
100
100
100
100
100
0252
Treecko
310
40
45
35
65
55
70
0253
Grovyle
405
50
65
45
85
65
95
0254
Sceptile
530
70
85
65
105
85
120
0254
Sceptile
630
70
110
75
145
85
145
0255
Torchic
310
45
60
40
70
50
45
0256
Combusken
405
60
85
60
85
60
55
0257
Blaziken
530
80
120
70
110
70
80
0257
Blaziken
630
80
160
80
130
80
100
0258
Mudkip
310
50
70
50
50
50
40
0259
Marshtomp
405
70
85
70
60
70
50
0260
Swampert
535
100
110
90
85
90
60
0260
Swampert
635
100
150
110
95
110
70
0261
Poochyena
220
35
55
35
30
30
35
0262
Mightyena
420
70
90
70
60
60
70
0263
Zigzagoon
240
38
30
41
30
41
60
0263
Zigzagoon
240
38
30
41
30
41
60
0264
Linoone
420
78
70
61
50
61
100
0264
Linoone
420
78
70
61
50
61
100
0265
Wurmple
195
45
45
35
20
30
20
0266
Silcoon
205
50
35
55
25
25
15
0267
Beautifly
395
60
70
50
100
50
65
0268
Cascoon
205
50
35
55
25
25
15
0269
Dustox
385
60
50
70
50
90
65
0270
Lotad
220
40
30
30
40
50
30
0271
Lombre
340
60
50
50
60
70
50
0272
Ludicolo
480
80
70
70
90
100
70
0273
Seedot
220
40
40
50
30
30
30
0274
Nuzleaf
340
70
70
40
60
40
60
0275
Shiftry
480
90
100
60
90
60
80
0276
Taillow
270
40
55
30
30
30
85
0277
Swellow
455
60
85
60
75
50
125
0278
Wingull
270
40
30
30
55
30
85
0279
Pelipper
440
60
50
100
95
70
65
0280
Ralts
198
28
25
25
45
35
40
0281
Kirlia
278
38
35
35
65
55
50
0282
Gardevoir
518
68
65
65
125
115
80
0282
Gardevoir
618
68
85
65
165
135
100
0283
Surskit
269
40
30
32
50
52
65
0284
Masquerain
454
70
60
62
100
82
80
0285
Shroomish
295
60
40
60
40
60
35
0286
Breloom
460
60
130
80
60
60
70
0287
Slakoth
280
60
60
60
35
35
30
0288
Vigoroth
440
80
80
80
55
55
90
0289
Slaking
670
150
160
100
95
65
100
0290
Nincada
266
31
45
90
30
30
40
0291
Ninjask
456
61
90
45
50
50
160
0292
Shedinja
236
1
90
45
30
30
40
0293
Whismur
240
64
51
23
51
23
28
0294
Loudred
360
84
71
43
71
43
48
0295
Exploud
490
104
91
63
91
73
68
0296
Makuhita
237
72
60
30
20
30
25
0297
Hariyama
474
144
120
60
40
60
50
0298
Azurill
190
50
20
40
20
40
20
0299
Nosepass
375
30
45
135
45
90
30
0300
Skitty
260
50
45
45
35
35
50
0301
Delcatty
400
70
65
65
55
55
90
0302
Sableye
380
50
75
75
65
65
50
0302
Sableye
480
50
85
125
85
115
20
0303
Mawile
380
50
85
85
55
55
50
0303
Mawile
480
50
105
125
55
95
50
0304
Aron
330
50
70
100
40
40
30
0305
Lairon
430
60
90
140
50
50
40
0306
Aggron
530
70
110
180
60
60
50
0306
Aggron
630
70
140
230
60
80
50
0307
Meditite
280
30
40
55
40
55
60
0308
Medicham
410
60
60
75
60
75
80
0308
Medicham
510
60
100
85
80
85
100
0309
Electrike
295
40
45
40
65
40
65
0310
Manectric
475
70
75
60
105
60
105
0310
Manectric
575
70
75
80
135
80
135
0311
Plusle
405
60
50
40
85
75
95
0312
Minun
405
60
40
50
75
85
95
0313
Volbeat
430
65
73
75
47
85
85
0314
Illumise
430
65
47
75
73
85
85
0315
Roselia
400
50
60
45
100
80
65
0316
Gulpin
302
70
43
53
43
53
40
0317
Swalot
467
100
73
83
73
83
55
0318
Carvanha
305
45
90
20
65
20
65
0319
Sharpedo
460
70
120
40
95
40
95
0319
Sharpedo
560
70
140
70
110
65
105
0320
Wailmer
400
130
70
35
70
35
60
0321
Wailord
500
170
90
45
90
45
60
0322
Numel
305
60
60
40
65
45
35
0323
Camerupt
460
70
100
70
105
75
40
0323
Camerupt
560
70
120
100
145
105
20
0324
Torkoal
470
70
85
140
85
70
20
0325
Spoink
330
60
25
35
70
80
60
0326
Grumpig
470
80
45
65
90
110
80
0327
Spinda
360
60
60
60
60
60
60
0328
Trapinch
290
45
100
45
45
45
10
0329
Vibrava
340
50
70
50
50
50
70
0330
Flygon
520
80
100
80
80
80
100
0331
Cacnea
335
50
85
40
85
40
35
0332
Cacturne
475
70
115
60
115
60
55
0333
Swablu
310
45
40
60
40
75
50
0334
Altaria
490
75
70
90
70
105
80
0334
Altaria
590
75
110
110
110
105
80
0335
Zangoose
458
73
115
60
60
60
90
0336
Seviper
458
73
100
60
100
60
65
0337
Lunatone
460
90
55
65
95
85
70
0338
Solrock
460
90
95
85
55
65
70
0339
Barboach
288
50
48
43
46
41
60
0340
Whiscash
468
110
78
73
76
71
60
0341
Corphish
308
43
80
65
50
35
35
0342
Crawdaunt
468
63
120
85
90
55
55
0343
Baltoy
300
40
40
55
40
70
55
0344
Claydol
500
60
70
105
70
120
75
0345
Lileep
355
66
41
77
61
87
23
0346
Cradily
495
86
81
97
81
107
43
0347
Anorith
355
45
95
50
40
50
75
0348
Armaldo
495
75
125
100
70
80
45
0349
Feebas
200
20
15
20
10
55
80
0350
Milotic
540
95
60
79
100
125
81
0351
Castform
420
70
70
70
70
70
70
0351
Castform
420
70
70
70
70
70
70
0351
Castform
420
70
70
70
70
70
70
0351
Castform
420
70
70
70
70
70
70
0352
Kecleon
440
60
90
70
60
120
40
0353
Shuppet
295
44
75
35
63
33
45
0354
Banette
455
64
115
65
83
63
65
0354
Banette
555
64
165
75
93
83
75
0355
Duskull
295
20
40
90
30
90
25
0356
Dusclops
455
40
70
130
60
130
25
0357
Tropius
460
99
68
83
72
87
51
0358
Chimecho
455
75
50
80
95
90
65
0359
Absol
465
65
130
60
75
60
75
0359
Absol
565
65
150
60
115
60
115
0360
Wynaut
260
95
23
48
23
48
23
0361
Snorunt
300
50
50
50
50
50
50
0362
Glalie
480
80
80
80
80
80
80
0362
Glalie
580
80
120
80
120
80
100
0363
Spheal
290
70
40
50
55
50
25
0364
Sealeo
410
90
60
70
75
70
45
0365
Walrein
530
110
80
90
95
90
65
0366
Clamperl
345
35
64
85
74
55
32
0367
Huntail
485
55
104
105
94
75
52
0368
Gorebyss
485
55
84
105
114
75
52
0369
Relicanth
485
100
90
130
45
65
55
0370
Luvdisc
330
43
30
55
40
65
97
0371
Bagon
300
45
75
60
40
30
50
0372
Shelgon
420
65
95
100
60
50
50
0373
Salamence
600
95
135
80
110
80
100
0373
Salamence
700
95
145
130
120
90
120
0374
Beldum
300
40
55
80
35
60
30
0375
Metang
420
60
75
100
55
80
50
0376
Metagross
600
80
135
130
95
90
70
0376
Metagross
700
80
145
150
105
110
110
0377
Regirock
580
80
100
200
50
100
50
0378
Regice
580
80
50
100
100
200
50
0379
Registeel
580
80
75
150
75
150
50
0380
Latias
600
80
80
90
110
130
110
0380
Latias
700
80
100
120
140
150
110
0381
Latios
600
80
90
80
130
110
110
0381
Latios
700
80
130
100
160
120
110
0382
Kyogre
670
100
100
90
150
140
90
0382
Kyogre
770
100
150
90
180
160
90
0383
Groudon
670
100
150
140
100
90
90
0383
Groudon
770
100
180
160
150
90
90
0384
Rayquaza
680
105
150
90
150
90
95
0384
Rayquaza
780
105
180
100
180
100
115
0385
Jirachi
600
100
100
100
100
100
100
0386
Deoxys
600
50
150
50
150
50
150
0386
Deoxys
600
50
180
20
180
20
150
0386
Deoxys
600
50
70
160
70
160
90
0386
Deoxys
600
50
95
90
95
90
180
0387
Turtwig
318
55
68
64
45
55
31
0388
Grotle
405
75
89
85
55
65
36
0389
Torterra
525
95
109
105
75
85
56
0390
Chimchar
309
44
58
44
58
44
61
0391
Monferno
405
64
78
52
78
52
81
0392
Infernape
534
76
104
71
104
71
108
0393
Piplup
314
53
51
53
61
56
40
0394
Prinplup
405
64
66
68
81
76
50
0395
Empoleon
530
84
86
88
111
101
60
0396
Starly
245
40
55
30
30
30
60
0397
Staravia
340
55
75
50
40
40
80
0398
Staraptor
485
85
120
70
50
60
100
0399
Bidoof
250
59
45
40
35
40
31
0400
Bibarel
410
79
85
60
55
60
71
0401
Kricketot
194
37
25
41
25
41
25
0402
Kricketune
384
77
85
51
55
51
65
0403
Shinx
263
45
65
34
40
34
45
0404
Luxio
363
60
85
49
60
49
60
0405
Luxray
523
80
120
79
95
79
70
0406
Budew
280
40
30
35
50
70
55
0407
Roserade
515
60
70
65
125
105
90
0408
Cranidos
350
67
125
40
30
30
58
0409
Rampardos
495
97
165
60
65
50
58
0410
Shieldon
350
30
42
118
42
88
30
0411
Bastiodon
495
60
52
168
47
138
30
0412
Burmy
224
40
29
45
29
45
36
0412
Burmy
224
40
29
45
29
45
36
0412
Burmy
224
40
29
45
29
45
36
0413
Wormadam
424
60
59
85
79
105
36
0413
Wormadam
424
60
79
105
59
85
36
0413
Wormadam
424
60
69
95
69
95
36
0414
Mothim
424
70
94
50
94
50
66
0415
Combee
244
30
30
42
30
42
70
0416
Vespiquen
474
70
80
102
80
102
40
0417
Pachirisu
405
60
45
70
45
90
95
0418
Buizel
330
55
65
35
60
30
85
0419
Floatzel
495
85
105
55
85
50
115
0420
Cherubi
275
45
35
45
62
53
35
0421
Cherrim
450
70
60
70
87
78
85
0422
Shellos
325
76
48
48
57
62
34
0423
Gastrodon
475
111
83
68
92
82
39
0424
Ambipom
482
75
100
66
60
66
115
0425
Drifloon
348
90
50
34
60
44
70
0426
Drifblim
498
150
80
44
90
54
80
0427
Buneary
350
55
66
44
44
56
85
0428
Lopunny
480
65
76
84
54
96
105
0428
Lopunny
580
65
136
94
54
96
135
0429
Mismagius
495
60
60
60
105
105
105
0430
Honchkrow
505
100
125
52
105
52
71
0431
Glameow
310
49
55
42
42
37
85
0432
Purugly
452
71
82
64
64
59
112
0433
Chingling
285
45
30
50
65
50
45
0434
Stunky
329
63
63
47
41
41
74
0435
Skuntank
479
103
93
67
71
61
84
0436
Bronzor
300
57
24
86
24
86
23
0437
Bronzong
500
67
89
116
79
116
33
0438
Bonsly
290
50
80
95
10
45
10
0439
Mime Jr.
310
20
25
45
70
90
60
0440
Happiny
220
100
5
5
15
65
30
0441
Chatot
411
76
65
45
92
42
91
0442
Spiritomb
485
50
92
108
92
108
35
0443
Gible
300
58
70
45
40
45
42
0444
Gabite
410
68
90
65
50
55
82
0445
Garchomp
600
108
130
95
80
85
102
0445
Garchomp
700
108
170
115
120
95
92
0446
Munchlax
390
135
85
40
40
85
5
0447
Riolu
285
40
70
40
35
40
60
0448
Lucario
525
70
110
70
115
70
90
0448
Lucario
625
70
145
88
140
70
112
0449
Hippopotas
330
68
72
78
38
42

In [103]:
# Creamos un data Frame con lo scrapeado

new = {"Pokedex_number":p,"Name":name,"Base_total":bt,"Hp":hp,"Defense":defense,"Attack":attack,"Sp_attack":spa,"Sp_defense":spd,"Speed":speed}
scrap = pd.DataFrame(new)
scrap["Pokedex_number"] = scrap["Pokedex_number"].astype(int)
scrap["Base_total"] = scrap["Base_total"].astype(int)
scrap["Hp"] = scrap["Hp"].astype(int)
scrap["Defense"] = scrap["Defense"].astype(int)
scrap["Attack"] = scrap["Attack"].astype(int)
scrap["Sp_attack"] = scrap["Sp_attack"].astype(int)
scrap["Sp_defense"] = scrap["Sp_defense"].astype(int)
scrap["Speed"] = scrap["Speed"].astype(int)
scrap.drop_duplicates(subset='Name',keep='first',inplace=True)
scrap.tail()

,Pokedex_number,Name,Base_total,Hp,Defense,Attack,Sp_attack,Sp_defense,Speed
1208,1021,Raging Bolt,590,125,91,73,137,89,75
1209,1022,Iron Boulder,590,90,80,120,68,108,124
1210,1023,Iron Crown,590,90,100,72,122,108,98
1211,1024,Terapagos,450,90,85,65,65,85,60
1214,1025,Pecharunt,600,88,160,88,88,88,88

In [104]:
# Añadimos los pokemons que nos faltan al DF original
scrap = scrap.loc[1067:]
pokemon = pd.concat([pokemon,scrap])
pokemon.tail()

,Pokedex_number,Name,Base_type,Secondary_type,Abilities,Generation,Legendary,Attack,Defense,Hp,Sp_attack,Sp_defense,Speed,Against_bug,Against_dark,Against_dragon,Against_electric,Against_fairy,Against_fight,Against_fire,Against_flying,Against_ghost,Against_grass,Against_ground,Against_ice,Against_normal,Against_poison,Against_psychic,Against_rock,Against_steel,Against_water,Base_egg_steps,Base_happiness,Base_total,Capture_rate,Experience_growth,Height_m,Weight_kg
1208,1021,Raging Bolt,NaN,NaN,NaN,NaN,NaN,73,91,125,137,89,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,590,NaN,NaN,NaN,NaN
1209,1022,Iron Boulder,NaN,NaN,NaN,NaN,NaN,120,80,90,68,108,124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,590,NaN,NaN,NaN,NaN
1210,1023,Iron Crown,NaN,NaN,NaN,NaN,NaN,72,100,90,122,108,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,590,NaN,NaN,NaN,NaN
1211,1024,Terapagos,NaN,NaN,NaN,NaN,NaN,65,85,90,65,85,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450,NaN,NaN,NaN,NaN
1214,1025,Pecharunt,NaN,NaN,NaN,NaN,NaN,88,160,88,88,88,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600,NaN,NaN,NaN,NaN

In [105]:
# Scrap de evoluciones de la API 

# Sacamos info adicional de la API de Pokemon
api_poke = []
poke_evol = []
conteo = 1
attempts = 0

# Usamos un while true para que hago mas intentos ya que hay casos en los que el status code era 400 y entonces paraba
while True:
    
    url = f"https://pokeapi.co/api/v2/evolution-chain/{conteo}"
    response = requests.get(url)
    if response.status_code != 200:
      attempts +=1
    else:
      # Guardamos el nombre del pokemon
        api_poke.append(response.json()["chain"]['species']["name"])

      # Guardaremos la evolucion de ese pokemon si tiene, si no, pondra que no tiene
        try:
          poke_evol.append(response.json()["chain"]["evolves_to"][0]["species"]["name"])
          print("Pokemon:", response.json()["chain"]['species']["name"])
        except:
            poke_evol.append("No hay")

    conteo +=1
          
    if attempts >= 15:
          
      break

print(len(api_poke),len(poke_evol))

Pokemon: bulbasaur
Pokemon: charmander
Pokemon: squirtle
Pokemon: caterpie
Pokemon: weedle
Pokemon: pidgey
Pokemon: rattata
Pokemon: spearow
Pokemon: ekans
Pokemon: pichu
Pokemon: sandshrew
Pokemon: nidoran-f
Pokemon: nidoran-m
Pokemon: cleffa
Pokemon: vulpix
Pokemon: igglybuff
Pokemon: zubat
Pokemon: oddish
Pokemon: paras
Pokemon: venonat
Pokemon: diglett
Pokemon: meowth
Pokemon: psyduck
Pokemon: mankey
Pokemon: growlithe
Pokemon: poliwag
Pokemon: abra
Pokemon: machop
Pokemon: bellsprout
Pokemon: tentacool
Pokemon: geodude
Pokemon: ponyta
Pokemon: slowpoke
Pokemon: magnemite
Pokemon: farfetchd
Pokemon: doduo
Pokemon: seel
Pokemon: grimer
Pokemon: shellder
Pokemon: gastly
Pokemon: onix
Pokemon: drowzee
Pokemon: krabby
Pokemon: voltorb
Pokemon: exeggcute
Pokemon: cubone
Pokemon: tyrogue
Pokemon: lickitung
Pokemon: koffing
Pokemon: rhyhorn
Pokemon: happiny
Pokemon: tangela
Pokemon: horsea
Pokemon: goldeen
Pokemon: staryu
Pokemon: mime-jr
Pokemon: scyther
Pokemon: smoochum
Pokemon: elekid
Pokemon: magby
Pokemon: magikarp
Pokemon: eevee
Pokemon: porygon
Pokemon: omanyte
Pokemon: kabuto
Pokemon: munchlax
Pokemon: dratini
Pokemon: chikorita
Pokemon: cyndaquil
Pokemon: totodile
Pokemon: sentret
Pokemon: hoothoot
Pokemon: ledyba
Pokemon: spinarak
Pokemon: chinchou
Pokemon: togepi
Pokemon: natu
Pokemon: mareep
Pokemon: azurill
Pokemon: bonsly
Pokemon: hoppip
Pokemon: aipom
Pokemon: sunkern
Pokemon: yanma
Pokemon: wooper
Pokemon: murkrow
Pokemon: misdreavus
Pokemon: wynaut
Pokemon: girafarig
Pokemon: pineco
Pokemon: dunsparce
Pokemon: gligar
Pokemon: snubbull
Pokemon: qwilfish
Pokemon: sneasel
Pokemon: teddiursa
Pokemon: slugma
Pokemon: swinub
Pokemon: corsola
Pokemon: remoraid
Pokemon: mantyke
Pokemon: houndour
Pokemon: phanpy
Pokemon: stantler
Pokemon: larvitar
Pokemon: treecko
Pokemon: torchic
Pokemon: mudkip
Pokemon: poochyena
Pokemon: zigzagoon
Pokemon: wurmple
Pokemon: lotad
Pokemon: seedot
Pokemon: taillow
Pokemon: wingull
Pokemon: ralts
Pokemon: surskit
Pokemon: shroomish
Pokemon: slakoth
Pokemon: nincada
Pokemon: whismur
Pokemon: makuhita
Pokemon: nosepass
Pokemon: skitty
Pokemon: aron
Pokemon: meditite
Pokemon: electrike
Pokemon: budew
Pokemon: gulpin
Pokemon: carvanha
Pokemon: wailmer
Pokemon: numel
Pokemon: spoink
Pokemon: trapinch
Pokemon: cacnea
Pokemon: swablu
Pokemon: barboach
Pokemon: corphish
Pokemon: baltoy
Pokemon: lileep
Pokemon: anorith
Pokemon: feebas
Pokemon: shuppet
Pokemon: duskull
Pokemon: chingling
Pokemon: snorunt
Pokemon: spheal
Pokemon: clamperl
Pokemon: bagon
Pokemon: beldum
Pokemon: turtwig
Pokemon: chimchar
Pokemon: piplup
Pokemon: starly
Pokemon: bidoof
Pokemon: kricketot
Pokemon: shinx
Pokemon: cranidos
Pokemon: shieldon
Pokemon: burmy
Pokemon: combee
Pokemon: buizel
Pokemon: cherubi
Pokemon: shellos
Pokemon: drifloon
Pokemon: buneary
Pokemon: glameow
Pokemon: stunky
Pokemon: bronzor
Pokemon: gible
Pokemon: riolu
Pokemon: hippopotas
Pokemon: skorupi
Pokemon: croagunk
Pokemon: finneon
Pokemon: snover
Pokemon: phione
Pokemon: snivy
Pokemon: tepig
Pokemon: oshawott
Pokemon: patrat
Pokemon: lillipup
Pokemon: purrloin
Pokemon: pansage
Pokemon: pansear
Pokemon: panpour
Pokemon: munna
Pokemon: pidove
Pokemon: blitzle
Pokemon: roggenrola
Pokemon: woobat
Pokemon: drilbur
Pokemon: timburr
Pokemon: tympole
Pokemon: sewaddle
Pokemon: venipede
Pokemon: cottonee
Pokemon: petilil
Pokemon: basculin
Pokemon: sandile
Pokemon: darumaka
Pokemon: dwebble
Pokemon: scraggy
Pokemon: yamask
Pokemon: tirtouga
Pokemon: archen
Pokemon: trubbish
Pokemon: zorua
Pokemon: minccino
Pokemon: gothita
Pokemon: solosis
Pokemon: ducklett
Pokemon: vanillite
Pokemon: deerling
Pokemon: karrablast
Pokemon: foongus
Pokemon: frillish
Pokemon: joltik
Pokemon: ferroseed
Pokemon: klink
Pokemon: tynamo
Pokemon: elgyem
Pokemon: litwick
Pokemon: axew
Pokemon: cubchoo
Pokemon: shelmet
Pokemon: mienfoo
Pokemon: golett
Pokemon: pawniard
Pokemon: rufflet
Pokemon: vullaby
Pokemon: deino
Pokemon: larvesta
Pokemon: chespin
Pokemon: fennekin
Pokemon: froakie
Pokemon: bunnelby
Pokemon: fletchling
Pokemon: scatterbug
Pokemon: litleo
Pokemon: flabebe
Pokemon: skiddo
Pokemon: pancham
Pokemon: espurr
Pokemon: honedge
Pokemon: spritzee
Pokemon: swirlix
Pokemon: inkay
Pokemon: binacle
Pokemon: skrelp
Pokemon: clauncher
Pokemon: helioptile
Pokemon: tyrunt
Pokemon: amaura
Pokemon: goomy
Pokemon: phantump
Pokemon: pumpkaboo
Pokemon: bergmite
Pokemon: noibat
Pokemon: rowlet
Pokemon: litten
Pokemon: popplio
Pokemon: pikipek
Pokemon: yungoos
Pokemon: grubbin
Pokemon: crabrawler
Pokemon: cutiefly
Pokemon: rockruff
Pokemon: mareanie
Pokemon: mudbray
Pokemon: dewpider
Pokemon: fomantis
Pokemon: morelull
Pokemon: salandit
Pokemon: stufful
Pokemon: bounsweet
Pokemon: wimpod
Pokemon: sandygast
Pokemon: type-null
Pokemon: jangmo-o
Pokemon: cosmog
Pokemon: poipole
Pokemon: grookey
Pokemon: scorbunny
Pokemon: sobble
Pokemon: skwovet
Pokemon: rookidee
Pokemon: blipbug
Pokemon: nickit
Pokemon: gossifleur
Pokemon: wooloo
Pokemon: chewtle
Pokemon: yamper
Pokemon: rolycoly
Pokemon: applin
Pokemon: silicobra
Pokemon: arrokuda
Pokemon: toxel
Pokemon: sizzlipede
Pokemon: clobbopus
Pokemon: sinistea
Pokemon: hatenna
Pokemon: impidimp
Pokemon: milcery
Pokemon: snom
Pokemon: cufant
Pokemon: duraludon
Pokemon: dreepy
Pokemon: kubfu
Pokemon: sprigatito
Pokemon: fuecoco
Pokemon: quaxly
Pokemon: lechonk
Pokemon: tarountula
Pokemon: nymble
Pokemon: pawmi
Pokemon: tandemaus
Pokemon: fidough
Pokemon: smoliv
Pokemon: nacli
Pokemon: charcadet
Pokemon: tadbulb
Pokemon: wattrel
Pokemon: maschiff
Pokemon: shroodle
Pokemon: bramblin
Pokemon: toedscool
Pokemon: capsakid
Pokemon: rellor
Pokemon: flittle
Pokemon: tinkatink
Pokemon: wiglett
Pokemon: finizen
Pokemon: varoom
Pokemon: glimmet
Pokemon: greavard
Pokemon: cetoddle
Pokemon: frigibax
Pokemon: gimmighoul
Pokemon: poltchageist
541 541

In [106]:
# Pasamos las listas a DataFrame
evolutions = pd.DataFrame()
evolutions["Name"] = api_poke
evolutions["Evolution"] = poke_evol

# Ponemos los nombres en mayuscula para poder hacer el merge correctamente

evolutions["Name"] = evolutions["Name"].apply(lambda x: str(x).capitalize())
evolutions["Evolution"] = evolutions["Evolution"].apply(lambda x: str(x).capitalize())

# Hacemos merge de los dos Dataframes

pokemon = pokemon.merge(evolutions, left_on="Name", right_on="Name", how="left")

In [107]:
# Re indexamos las columnas para que sea mas facil trabajar

pokemon = pokemon.loc[:,['Pokedex_number', 'Name', 'Evolution', 'Base_type', 'Secondary_type',
       'Abilities', 'Generation', 'Legendary', 'Attack', 'Defense', 'Hp',
       'Sp_attack', 'Sp_defense', 'Speed', 'Height_m','Weight_kg', 'Against_bug', 'Against_dark',
       'Against_dragon', 'Against_electric', 'Against_fairy', 'Against_fight',
       'Against_fire', 'Against_flying', 'Against_ghost', 'Against_grass',
       'Against_ground', 'Against_ice', 'Against_normal', 'Against_poison',
       'Against_psychic', 'Against_rock', 'Against_steel', 'Against_water',
       'Base_egg_steps', 'Base_happiness', 'Base_total', 'Capture_rate',
       'Experience_growth'
        ]]

In [108]:
# Hacemos un fillna para poder filtrar por nulos y corregir las evoluciones

pokemon["Evolution"].fillna("Unknown",inplace=True)

# Corregimos evoluciones que faltaban

evol = {1:"Venusaur",
        4:"Charizard",
        7:"Blastoise",
        10:"Butterfree",
        13:"Beedrill",
        16:"Pidgeot",
        24:"Raichu",
        28:"Nidorina",
        29:"Nidoqueen",
        31:"Nidorino",
        32:"Nidoking",
        34:"Clefable",
        38:"Wigglytuff",
        41:"Crobat",
        43:"Vileplum",
        60:"Poliwrath",
        63:"Alakazam",
        66:"Machamp",
        69:"Victreebel",
        74:"Golem",
        92:"Gengar",
        116:"Kingdra",
        147:"Dragonite",
        153:"Meganium",
        155:"Typhlosion",
        158:"Feraligatr",
        182:"Azumarill",
        246:"Tyranitar",
        252:"Sceptile",
        256:"Blaziken",
        259:"Swampert",
        270:"Ludicolo",
        273:"Shiftry",
        280:"Gardevoir",
        287:"Slaking",
        290:"Shedinja",
        293:"Exploud",
        304:"Aggron",
        363:"Walrein",
        372:"Salamance",
        375:"Metagross",
        387:"Torterra",
        391:"Infernape",
        394:"Empoleon",
        396:"Staraptor",
        403:"Luxray",
        443:"Garchomp",
        495:"Serperior",
        498:"Emboar",
        501:"Samurott",
        507:"Stoutland",
        519:"Unfezant",
        525:"Gigalith",
        532:"Conkeldurr",
        535:"Seismitoad",
        540:"Leavanny",
        543:"Scolipede",
        551:"Krookodile",
        574:"Gothitelle",
        577:"Reuniclus",
        582:"Vanilluxe",
        599:"Klinklang",
        602:"Eelektross",
        607:"Chandelure",
        610:"Haxorus",
        650:"Chesnaught",
        653:"Delphox",
        656:"Greninja",
        661:"Talonflame",
        664:"Vivillion",
        668:"Floette",
        669:"Florges",
        679:"Aegislash",
        704:"Goodra",
        723:"Decidueye",
        726:"Incineroar",
        728:"Primarina",
        731:"Toucannon",
        736:"Vikavolt",
        761:"Tsareena",
        772:"Silvally",
        783:"Kommo-o",
        801:"Perrserker",
        802:"Galarian Rapidash",
        804: "Galarian Slowbro",
        806:"Galarian Sirfetch'd",
        807: "Galarian Koofing",
        808: "Galarian Mr.Rime",
        813: "Cursola",
        814: "Galarian Linoone",
        815: "Obstagoon",
        817: "Darmanitan",
        819: "Runerigus"


        }
pokemon["Evolution"].update(pd.Series(evol))

In [109]:
# Scrapeamos 9 generacion y sus tipos

PATH=("C:\Program Files (x86)\chromedriver.exe")
driver=webdriver.Chrome(PATH)
driver.get("https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number#List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number")
time.sleep(5)
new_gen = []
tipo1 = []
tipo2 = []

# Looping to get names
for i in range(2,136):
    try:

        name = driver.find_element_by_xpath(f'//*[@id="mw-content-text"]/div[1]/table[10]/tbody/tr[{i}]/td[3]/a').text
        new_gen.append(name)
        print(name)
        # Try to save first type
        try:
            t = driver.find_element_by_xpath(f'//*[@id="mw-content-text"]/div[1]/table[10]/tbody/tr[{i}]/td[4]').text
            tipo1.append(t)
            print(tipo1)
        
        except:
            tipo1.append(None)

    # Try to get second type
        try:
            
            t2 = driver.find_element_by_xpath(f'//*[@id="mw-content-text"]/div[1]/table[10]/tbody/tr[{i}]/td[5]').text
            tipo2.append(t2)
            print(tipo2)
        
        except:
            tipo2.append(None)
    except:
        driver.close()
driver.close()
# Convertimos a DataFrame la info
p = {"Name":new_gen,"Type_1":tipo1,"Type_2":tipo2}
scraped = pd.DataFrame(p)
scraped.tail()

Sprigatito
['Grass']
Floragato
['Grass', 'Grass']
Meowscarada
['Grass', 'Grass', 'Grass']
[None, None, 'Dark']
Fuecoco
['Grass', 'Grass', 'Grass', 'Fire']
Crocalor
['Grass', 'Grass', 'Grass', 'Fire', 'Fire']
Skeledirge
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire']
[None, None, 'Dark', None, None, 'Ghost']
Quaxly
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water']
Quaxwell
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water']
Quaquaval
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting']
Lechonk
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal']
Oinkologne
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal']
Normal
Tarountula
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug']
Spidops
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug']
Nymble
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug']
Lokix
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark']
Pawmi
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric']
Pawmo
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting']
Pawmot
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting']
Tandemaus
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal']
Maushold
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal']
Normal
Fidough
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy']
Dachsbun
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy']
Smoliv
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal']
Dolliv
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal']
Arboliva
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal']
Squawkabilly
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying']
Normal
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying']
Normal
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying']
Normal
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying']
Nacli
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock']
Naclstack
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock']
Garganacl
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock']
Charcadet
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire']
Armarouge
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic']
Ceruledge
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic', 'Ghost']
Tadbulb
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric']
Bellibolt
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric']
Wattrel
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic', 'Ghost', None, None, 'Flying']
Kilowattrel
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic', 'Ghost', None, None, 'Flying', 'Flying']
Maschiff
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark']
Mabosstiff
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark']
Shroodle
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic', 'Ghost', None, None, 'Flying', 'Flying', None, None, 'Normal']
Grafaiai
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic', 'Ghost', None, None, 'Flying', 'Flying', None, None, 'Normal', 'Normal']
Bramblin
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison', 'Grass']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic', 'Ghost', None, None, 'Flying', 'Flying', None, None, 'Normal', 'Normal', 'Ghost']
Brambleghast
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison', 'Grass', 'Grass']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic', 'Ghost', None, None, 'Flying', 'Flying', None, None, 'Normal', 'Normal', 'Ghost', 'Ghost']
Toedscool
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison', 'Grass', 'Grass', 'Ground']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic', 'Ghost', None, None, 'Flying', 'Flying', None, None, 'Normal', 'Normal', 'Ghost', 'Ghost', 'Grass']
Toedscruel
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison', 'Grass', 'Grass', 'Ground', 'Ground']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic', 'Ghost', None, None, 'Flying', 'Flying', None, None, 'Normal', 'Normal', 'Ghost', 'Ghost', 'Grass', 'Grass']
Klawf
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison', 'Grass', 'Grass', 'Ground', 'Ground', 'Rock']
Capsakid
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison', 'Grass', 'Grass', 'Ground', 'Ground', 'Rock', 'Grass']
Scovillain
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison', 'Grass', 'Grass', 'Ground', 'Ground', 'Rock', 'Grass', 'Grass']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic', 'Ghost', None, None, 'Flying', 'Flying', None, None, 'Normal', 'Normal', 'Ghost', 'Ghost', 'Grass', 'Grass', None, None, 'Fire']
Rellor
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison', 'Grass', 'Grass', 'Ground', 'Ground', 'Rock', 'Grass', 'Grass', 'Bug']
Rabsca
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison', 'Grass', 'Grass', 'Ground', 'Ground', 'Rock', 'Grass', 'Grass', 'Bug', 'Bug']
[None, None, 'Dark', None, None, 'Ghost', None, None, 'Fighting', None, None, None, None, None, None, 'Dark', None, 'Fighting', 'Fighting', None, None, None, None, None, 'Normal', 'Normal', 'Normal', 'Flying', None, None, None, None, None, None, None, 'Psychic', 'Ghost', None, None, 'Flying', 'Flying', None, None, 'Normal', 'Normal', 'Ghost', 'Ghost', 'Grass', 'Grass', None, None, 'Fire', None, 'Psychic']
Flittle
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison', 'Grass', 'Grass', 'Ground', 'Ground', 'Rock', 'Grass', 'Grass', 'Bug', 'Bug', 'Psychic']
Espathra
['Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water', 'Water', 'Water', 'Normal', 'Normal', None, 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric', 'Normal', 'Normal', None, 'Fairy', 'Fairy', 'Grass', 'Grass', 'Grass', 'Normal', 'Flying', 'Flying', 'Flying', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Electric', 'Dark', 'Dark', 'Poison', 'Poison', 'Grass', 'Grass', 'Ground', 'Ground', 'Rock', 'Grass', 'Grass', 'Bug', 'Bug', 'Psychic', 'Psychic']
Tinkatink

             Name  Type_1   Type_2
129  Iron Boulder    Rock  Psychic
130    Iron Crown   Steel  Psychic
131     Terapagos  Normal     None
132        Normal    None     None
133     Pecharunt  Poison    Ghost

In [110]:
#Hacemos merge para poder juntar los types segun el nombre
pokemon = pokemon.merge(scraped, left_on="Name", right_on="Name", how="left")
gen9_type = scraped["Name"].to_list()
pokemon["Base_type"] = pokemon.apply(lambda x: x["Type_1"] if x["Name"] in gen9_type else x["Base_type"], axis=1)

pokemon["Secondary_type"] = pokemon.apply(lambda x: x["Type_2"] if x["Name"] in gen9_type else x["Secondary_type"], axis=1)

In [111]:
# Dropeamos las columnas que no necesitamos de type
pokemon.drop(columns=["Type_1","Type_2"], axis=1,inplace=True)

# Ponemos todos los tipos capitalizados
pokemon["Base_type"] = pokemon["Base_type"].apply(lambda x: str(x).capitalize())
pokemon["Secondary_type"] = pokemon["Secondary_type"].apply(lambda x: str(x).capitalize())

In [168]:
# Guardamos a csv

pokemon.to_csv('pokemon_casi.csv')
pokemon_casi = pd.read_csv('pokemon_casi.csv')

In [143]:
# Scrapeamos las habilidades y otros stats de la generacion 9

PATH=("C:\Program Files (x86)\chromedriver.exe")
driver=webdriver.Chrome(PATH)
driver.get("https://pokemondb.net/pokedex/all")
time.sleep(2)
numero = []
nombre = []
abilities = []
altura = []
peso = []
egg_step = []
capture = []
# Lo incializamos con este valor porque ahi empieza lo que nos interesa
contador = 899
# Generamos otro contador para ir haciendo append en la lista de listas para las habilidades
counter = 0
# Looping to get pokedex number + stats
for i in range(1070,1216):

    
    driver.find_element(By.XPATH, f'//*[@id="pokedex"]/tbody/tr[{i}]/td[2]/a').click()
    time.sleep(2)
    n = driver.find_element(By.XPATH, f'//*[@id="main"]/h1').text
    nombre.append(n)
    print(n)
    numero.append(i)
    abilities.append(i)
    print(i)

    # SI existe un pokemon con el mismo numero entonces scrapeamos primero el inicial y luego el siguiente:
    try:       
        # SI solo tiene una habilidad
        try:
            # Intentamos coger las habilidades segun el numero que tengan
            try:
                for z in range(1,3):    
                    ab = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[6]/td/span[{z}]/a').text
                    abilities.append(ab)
                    print(ab)
                   
                                
                ab2 = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[6]/td/small/a').text
                abilities.append(ab2)
                print(ab2)  

            except:

                ab = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[6]/td/span/a').text
                abilities.append(ab)
                print(ab)
                ab2 = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[6]/td/small/a').text
                abilities.append(ab2)
                print(ab2)
        except:

            ab = driver.find_element(By.XPATH, f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[6]/td/span/a').text
            abilities.append(ab)
            print(ab)
            
            
        alt = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[4]/td').text
        altura.append(alt)
        print(alt)

        ps = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[5]/td').text
        peso.append(ps)
        print(ps)

        try:    
            eg = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[3]/div/div[2]/table/tbody/tr[3]/td/small').text
            egg_step.append(eg)
            print(eg)
        except:

            eg = driver.find_element(By.XPATH, f'//*[@id="tab-basic-{contador}"]/div[1]/div[3]/div/div[2]/table/tbody/tr[3]/td').text

        cap = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[3]/div/div[1]/table/tbody/tr[2]/td').text
        capture.append(cap)
        print(cap)
        
        contador+=1
    # SI existe un pokemon con el mismo numero entonces scrapeamos primero el inicial y luego el siguiente:
    except:
        contador-=1
        try:
        # Intentamos coger las habilidades segun el numero que tengan
            try:
                for z in range(1,3):    
                    ab = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[6]/td/span[{z}]/a').text
                    abilities.append(ab)
                    print(ab)
                    
                    
                ab2 = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[6]/td/small/a').text
                abilities.append(ab2)
                print(ab2)  

            except:

                ab = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[6]/td/span/a').text
                abilities.append(ab)
                print(ab)
                ab2 = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[6]/td/small/a').text
                abilities.append(ab2)
                print(ab2)
        except:

            ab = driver.find_element(By.XPATH, f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[6]/td/span/a').text
            abilities.append(ab)
            print(ab)

        alt = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[4]/td').text
        altura.append(alt)
        print(alt)

        ps = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[2]/table/tbody/tr[5]/td').text
        peso.append(ps)
        print(ps)

        try:    
            eg = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[3]/div/div[2]/table/tbody/tr[3]/td/small').text
            egg_step.append(eg)
            print(eg)
        except:

            eg = driver.find_element(By.XPATH, f'//*[@id="tab-basic-{contador}"]/div[1]/div[3]/div/div[2]/table/tbody/tr[3]/td').text

        cap = driver.find_element(By.XPATH,f'//*[@id="tab-basic-{contador}"]/div[1]/div[3]/div/div[1]/table/tbody/tr[2]/td').text
        capture.append(cap)
        print(cap)

        
        contador+=1
   
        
    driver.back()
    time.sleep(1)

driver.close()

Calyrex
1070
Unnerve
Unnerve
Unnerve
1.1 m (3′07″)
7.7 kg (17.0 lbs)
(30,584–30,840 steps)
3 (0.4% with PokéBall, full HP)
Wyrdeer
1071
Intimidate
Frisk
Sap Sipper
1.8 m (5′11″)
95.1 kg (209.7 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Kleavor
1072
Swarm
Sheer Force
Sharpness
1.8 m (5′11″)
89.0 kg (196.2 lbs)
(4,884–5,140 steps)
15 (2.0% with PokéBall, full HP)
Ursaluna
1073
Guts
Bulletproof
Unnerve
2.4 m (7′10″)
290.0 kg (639.3 lbs)
(4,884–5,140 steps)
20 (2.6% with PokéBall, full HP)
Ursaluna
1074
Guts
Bulletproof
Unnerve
2.4 m (7′10″)
290.0 kg (639.3 lbs)
(4,884–5,140 steps)
20 (2.6% with PokéBall, full HP)
Basculegion
1075
Swift Swim
Adaptability
Mold Breaker
3.0 m (9′10″)
110.0 kg (242.5 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Basculegion
1076
Swift Swim
Adaptability
Mold Breaker
3.0 m (9′10″)
110.0 kg (242.5 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Sneasler
1077
Pressure
Unburden
Poison Touch
1.3 m (4′03″)
43.0 kg (94.8 lbs)
(4,884–5,140 steps)
20 (2.6% with PokéBall, full HP)
Overqwil
1078
Poison Point
Swift Swim
Intimidate
2.5 m (8′02″)
60.5 kg (133.4 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Enamorus
1079
Cute Charm
Cute Charm
Contrary
1.6 m (5′03″)
48.0 kg (105.8 lbs)
(4,884–5,140 steps)
3 (0.4% with PokéBall, full HP)
Enamorus
1080
Cute Charm
Cute Charm
Contrary
1.6 m (5′03″)
48.0 kg (105.8 lbs)
(4,884–5,140 steps)
3 (0.4% with PokéBall, full HP)
Sprigatito
1081
Overgrow
Overgrow
Protean
0.4 m (1′04″)
4.1 kg (9.0 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Floragato
1082
Overgrow
Overgrow
Protean
0.9 m (2′11″)
12.2 kg (26.9 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Meowscarada
1083
Overgrow
Overgrow
Protean
1.5 m (4′11″)
31.2 kg (68.8 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Fuecoco
1084
Blaze
Blaze
Unaware
0.4 m (1′04″)
9.8 kg (21.6 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Crocalor
1085
Blaze
Blaze
Unaware
1.0 m (3′03″)
30.7 kg (67.7 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Skeledirge
1086
Blaze
Blaze
Unaware
1.6 m (5′03″)
326.5 kg (719.8 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Quaxly
1087
Torrent
Torrent
Moxie
0.5 m (1′08″)
6.1 kg (13.4 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Quaxwell
1088
Torrent
Torrent
Moxie
1.2 m (3′11″)
21.5 kg (47.4 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Quaquaval
1089
Torrent
Torrent
Moxie
1.8 m (5′11″)
61.9 kg (136.5 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Lechonk
1090
Aroma Veil
Gluttony
Thick Fat
0.5 m (1′08″)
10.2 kg (22.5 lbs)
(3,599–3,855 steps)
255 (33.3% with PokéBall, full HP)
Oinkologne
1091
Lingering Aroma
Gluttony
Thick Fat
1.0 m (3′03″)
120.0 kg (264.6 lbs)
(3,599–3,855 steps)
100 (13.1% with PokéBall, full HP)
Oinkologne
1092
Lingering Aroma
Gluttony
Thick Fat
1.0 m (3′03″)
120.0 kg (264.6 lbs)
(3,599–3,855 steps)
100 (13.1% with PokéBall, full HP)
Tarountula
1093
Insomnia
Insomnia
Stakeout
0.3 m (1′00″)
4.0 kg (8.8 lbs)
(3,599–3,855 steps)
255 (33.3% with PokéBall, full HP)
Spidops
1094
Insomnia
Insomnia
Stakeout
1.0 m (3′03″)
16.5 kg (36.4 lbs)
(3,599–3,855 steps)
120 (15.7% with PokéBall, full HP)
Nymble
1095
Swarm
Swarm
Tinted Lens
0.2 m (0′08″)
1.0 kg (2.2 lbs)
(4,884–5,140 steps)
190 (24.8% with PokéBall, full HP)
Lokix
1096
Swarm
Swarm
Tinted Lens
1.0 m (3′03″)
17.5 kg (38.6 lbs)
(4,884–5,140 steps)
30 (3.9% with PokéBall, full HP)
Pawmi
1097
Static
Natural Cure
Iron Fist
0.3 m (1′00″)
2.5 kg (5.5 lbs)
(3,599–3,855 steps)
190 (24.8% with PokéBall, full HP)
Pawmo
1098
Volt Absorb
Natural Cure
Iron Fist
0.4 m (1′04″)
6.5 kg (14.3 lbs)
(3,599–3,855 steps)
80 (10.5% with PokéBall, full HP)
Pawmot
1099
Volt Absorb
Natural Cure
Iron Fist
0.9 m (2′11″)
41.0 kg (90.4 lbs)
(3,599–3,855 steps)
45 (5.9% with PokéBall, full HP)
Tandemaus
1100
Run Away
Pickup
Own Tempo
0.3 m (1′00″)
1.8 kg (4.0 lbs)
(2,314–2,570 steps)
150 (19.6% with PokéBall, full HP)
Maushold
1101
Friend Guard
Cheek Pouch
Technician
0.3 m (1′00″)
2.8 kg (6.2 lbs)
(2,314–2,570 steps)
75 (9.8% with PokéBall, full HP)
Maushold
1102
Friend Guard
Cheek Pouch
Technician
0.3 m (1′00″)
2.8 kg (6.2 lbs)
(2,314–2,570 steps)
75 (9.8% with PokéBall, full HP)
Fidough
1103
Own Tempo
Own Tempo
Klutz
0.3 m (1′00″)
10.9 kg (24.0 lbs)
(4,884–5,140 steps)
190 (24.8% with PokéBall, full HP)
Dachsbun
1104
Well-Baked Body
Well-Baked Body
Aroma Veil
0.5 m (1′08″)
14.9 kg (32.8 lbs)
(4,884–5,140 steps)
90 (11.8% with PokéBall, full HP)
Smoliv
1105
Early Bird
Early Bird
Harvest
0.3 m (1′00″)
6.5 kg (14.3 lbs)
(4,884–5,140 steps)
255 (33.3% with PokéBall, full HP)
Dolliv
1106
Early Bird
Early Bird
Harvest
0.6 m (2′00″)
11.9 kg (26.2 lbs)
(4,884–5,140 steps)
120 (15.7% with PokéBall, full HP)
Arboliva
1107
Seed Sower
Seed Sower
Harvest
1.4 m (4′07″)
48.2 kg (106.3 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Squawkabilly
1108
Intimidate
Hustle
Guts
0.6 m (2′00″)
2.4 kg (5.3 lbs)
(3,599–3,855 steps)
190 (24.8% with PokéBall, full HP)
Squawkabilly
1109
Intimidate
Hustle
Guts
0.6 m (2′00″)
2.4 kg (5.3 lbs)
(3,599–3,855 steps)
190 (24.8% with PokéBall, full HP)
Squawkabilly
1110
Intimidate
Hustle
Guts
0.6 m (2′00″)
2.4 kg (5.3 lbs)
(3,599–3,855 steps)
190 (24.8% with PokéBall, full HP)
Squawkabilly
1111
Intimidate
Hustle
Guts
0.6 m (2′00″)
2.4 kg (5.3 lbs)
(3,599–3,855 steps)
190 (24.8% with PokéBall, full HP)
Nacli
1112
Purifying Salt
Sturdy
Clear Body
0.4 m (1′04″)
16.0 kg (35.3 lbs)
(4,884–5,140 steps)
255 (33.3% with PokéBall, full HP)
Naclstack
1113
Purifying Salt
Sturdy
Clear Body
0.6 m (2′00″)
105.0 kg (231.5 lbs)
(4,884–5,140 steps)
120 (15.7% with PokéBall, full HP)
Garganacl
1114
Purifying Salt
Sturdy
Clear Body
2.3 m (7′07″)
240.0 kg (529.1 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Charcadet
1115
Flash Fire
Flash Fire
Flame Body
0.6 m (2′00″)
10.5 kg (23.1 lbs)
(8,739–8,995 steps)
90 (11.8% with PokéBall, full HP)
Armarouge
1116
Flash Fire
Flash Fire
Weak Armor
1.5 m (4′11″)
85.0 kg (187.4 lbs)
(8,739–8,995 steps)
25 (3.3% with PokéBall, full HP)
Ceruledge
1117
Flash Fire
Flash Fire
Weak Armor
1.6 m (5′03″)
62.0 kg (136.7 lbs)
(8,739–8,995 steps)
25 (3.3% with PokéBall, full HP)
Tadbulb
1118
Own Tempo
Static
Damp
0.3 m (1′00″)
0.4 kg (0.9 lbs)
(4,884–5,140 steps)
190 (24.8% with PokéBall, full HP)
Bellibolt
1119
Electromorphosis
Static
Damp
1.2 m (3′11″)
113.0 kg (249.1 lbs)
(4,884–5,140 steps)
50 (6.5% with PokéBall, full HP)
Wattrel
1120
Wind Power
Volt Absorb
Competitive
0.4 m (1′04″)
3.6 kg (7.9 lbs)
(4,884–5,140 steps)
180 (23.5% with PokéBall, full HP)
Kilowattrel
1121
Wind Power
Volt Absorb
Competitive
1.4 m (4′07″)
38.6 kg (85.1 lbs)
(4,884–5,140 steps)
90 (11.8% with PokéBall, full HP)
Maschiff
1122
Intimidate
Run Away
Stakeout
0.5 m (1′08″)
16.0 kg (35.3 lbs)
(4,884–5,140 steps)
150 (19.6% with PokéBall, full HP)
Mabosstiff
1123
Intimidate
Guard Dog
Stakeout
1.1 m (3′07″)
61.0 kg (134.5 lbs)
(4,884–5,140 steps)
75 (9.8% with PokéBall, full HP)
Shroodle
1124
Unburden
Pickpocket
Prankster
0.2 m (0′08″)
0.7 kg (1.5 lbs)
(4,884–5,140 steps)
190 (24.8% with PokéBall, full HP)
Grafaiai
1125
Unburden
Poison Touch
Prankster
0.7 m (2′04″)
27.2 kg (60.0 lbs)
(4,884–5,140 steps)
90 (11.8% with PokéBall, full HP)
Bramblin
1126
Wind Rider
Wind Rider
Infiltrator
0.6 m (2′00″)
0.6 kg (1.3 lbs)
(4,884–5,140 steps)
190 (24.8% with PokéBall, full HP)
Brambleghast
1127
Wind Rider
Wind Rider
Infiltrator
1.2 m (3′11″)
6.0 kg (13.2 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Toedscool
1128
Mycelium Might
Mycelium Might
Mycelium Might
0.9 m (2′11″)
33.0 kg (72.8 lbs)
(4,884–5,140 steps)
190 (24.8% with PokéBall, full HP)
Toedscruel
1129
Mycelium Might
Mycelium Might
Mycelium Might
1.9 m (6′03″)
58.0 kg (127.9 lbs)
(4,884–5,140 steps)
90 (11.8% with PokéBall, full HP)
Klawf
1130
Anger Shell
Shell Armor
Regenerator
1.3 m (4′03″)
79.0 kg (174.2 lbs)
(8,739–8,995 steps)
120 (15.7% with PokéBall, full HP)
Capsakid
1131
Chlorophyll
Insomnia
Klutz
0.3 m (1′00″)
3.0 kg (6.6 lbs)
(4,884–5,140 steps)
190 (24.8% with PokéBall, full HP)
Scovillain
1132
Chlorophyll
Insomnia
Moody
0.9 m (2′11″)
15.0 kg (33.1 lbs)
(4,884–5,140 steps)
75 (9.8% with PokéBall, full HP)
Rellor
1133
Compound Eyes
Compound Eyes
Shed Skin
0.2 m (0′08″)
1.0 kg (2.2 lbs)
(4,884–5,140 steps)
190 (24.8% with PokéBall, full HP)
Rabsca
1134
Synchronize
Synchronize
Telepathy
0.3 m (1′00″)
3.5 kg (7.7 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Flittle
1135
Anticipation
Frisk
Speed Boost
0.2 m (0′08″)
1.5 kg (3.3 lbs)
(4,884–5,140 steps)
120 (15.7% with PokéBall, full HP)
Espathra
1136
Opportunist
Frisk
Speed Boost
1.9 m (6′03″)
90.0 kg (198.4 lbs)
(4,884–5,140 steps)
60 (7.8% with PokéBall, full HP)
Tinkatink
1137
Mold Breaker
Own Tempo
Pickpocket
0.4 m (1′04″)
8.9 kg (19.6 lbs)
(4,884–5,140 steps)
190 (24.8% with PokéBall, full HP)
Tinkatuff
1138
Mold Breaker
Own Tempo
Pickpocket
0.7 m (2′04″)
59.1 kg (130.3 lbs)
(4,884–5,140 steps)
90 (11.8% with PokéBall, full HP)
Tinkaton
1139
Mold Breaker
Own Tempo
Pickpocket
0.7 m (2′04″)
112.8 kg (248.7 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Wiglett
1140
Gooey
Rattled
Sand Veil
1.2 m (3′11″)
1.8 kg (4.0 lbs)
(4,884–5,140 steps)
255 (33.3% with PokéBall, full HP)
Wugtrio
1141
Gooey
Rattled
Sand Veil
1.2 m (3′11″)
5.4 kg (11.9 lbs)
(4,884–5,140 steps)
50 (6.5% with PokéBall, full HP)
Bombirdier
1142
Big Pecks
Keen Eye
Rocky Payload
1.5 m (4′11″)
42.9 kg (94.6 lbs)
(8,739–8,995 steps)
25 (3.3% with PokéBall, full HP)
Finizen
1143
Water Veil
Water Veil
Water Veil
1.3 m (4′03″)
60.2 kg (132.7 lbs)
(10,024–10,280 steps)
200 (26.1% with PokéBall, full HP)
Palafin
1144
Zero to Hero
Zero to Hero
Zero to Hero
1.3 m (4′03″)
60.2 kg (132.7 lbs)
(10,024–10,280 steps)
45 (5.9% with PokéBall, full HP)
Palafin
1145
Zero to Hero
Zero to Hero
Zero to Hero
1.3 m (4′03″)
60.2 kg (132.7 lbs)
(10,024–10,280 steps)
45 (5.9% with PokéBall, full HP)
Varoom
1146
Overcoat
Overcoat
Slow Start
1.0 m (3′03″)
35.0 kg (77.2 lbs)
(4,884–5,140 steps)
190 (24.8% with PokéBall, full HP)
Revavroom
1147
Overcoat
Overcoat
Filter
1.8 m (5′11″)
120.0 kg (264.6 lbs)
(4,884–5,140 steps)
75 (9.8% with PokéBall, full HP)
Cyclizar
1148
Shed Skin
Shed Skin
Regenerator
1.6 m (5′03″)
63.0 kg (138.9 lbs)
(7,454–7,710 steps)
190 (24.8% with PokéBall, full HP)
Orthworm
1149
Earth Eater
Earth Eater
Sand Veil
2.5 m (8′02″)
310.0 kg (683.4 lbs)
(8,739–8,995 steps)
25 (3.3% with PokéBall, full HP)
Glimmet
1150
Toxic Debris
Toxic Debris
Corrosion
0.7 m (2′04″)
8.0 kg (17.6 lbs)
(7,454–7,710 steps)
70 (9.1% with PokéBall, full HP)
Glimmora
1151
Toxic Debris
Toxic Debris
Corrosion
1.5 m (4′11″)
45.0 kg (99.2 lbs)
(7,454–7,710 steps)
25 (3.3% with PokéBall, full HP)
Greavard
1152
Pickup
Pickup
Fluffy
0.6 m (2′00″)
35.0 kg (77.2 lbs)
(4,884–5,140 steps)
120 (15.7% with PokéBall, full HP)
Houndstone
1153
Sand Rush
Sand Rush
Fluffy
2.0 m (6′07″)
15.0 kg (33.1 lbs)
(4,884–5,140 steps)
60 (7.8% with PokéBall, full HP)
Flamigo
1154
Scrappy
Tangled Feet
Costar
1.6 m (5′03″)
37.0 kg (81.6 lbs)
(4,884–5,140 steps)
100 (13.1% with PokéBall, full HP)
Cetoddle
1155
Thick Fat
Snow Cloak
Sheer Force
1.2 m (3′11″)
45.0 kg (99.2 lbs)
(6,169–6,425 steps)
150 (19.6% with PokéBall, full HP)
Cetitan
1156
Thick Fat
Slush Rush
Sheer Force
4.5 m (14′09″)
700.0 kg (1543.2 lbs)
(6,169–6,425 steps)
50 (6.5% with PokéBall, full HP)
Veluza
1157
Mold Breaker
Mold Breaker
Sharpness
2.5 m (8′02″)
90.0 kg (198.4 lbs)
(4,884–5,140 steps)
100 (13.1% with PokéBall, full HP)
Dondozo
1158
Unaware
Oblivious
Water Veil
12.0 m (39′04″)
220.0 kg (485.0 lbs)
(10,024–10,280 steps)
25 (3.3% with PokéBall, full HP)
Tatsugiri
1159
Commander
Commander
Storm Drain
0.3 m (1′00″)
8.0 kg (17.6 lbs)
(8,739–8,995 steps)
100 (13.1% with PokéBall, full HP)
Tatsugiri
1160
Commander
Commander
Storm Drain
0.3 m (1′00″)
8.0 kg (17.6 lbs)
(8,739–8,995 steps)
100 (13.1% with PokéBall, full HP)
Tatsugiri
1161
Commander
Commander
Storm Drain
0.3 m (1′00″)
8.0 kg (17.6 lbs)
(8,739–8,995 steps)
100 (13.1% with PokéBall, full HP)
Annihilape
1162
Vital Spirit
Inner Focus
Defiant
1.2 m (3′11″)
56.0 kg (123.5 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Clodsire
1163
Poison Point
Water Absorb
Unaware
1.8 m (5′11″)
223.0 kg (491.6 lbs)
(4,884–5,140 steps)
90 (11.8% with PokéBall, full HP)
Farigiraf
1164
Cud Chew
Armor Tail
Sap Sipper
3.2 m (10′06″)
160.0 kg (352.7 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Dudunsparce
1165
Serene Grace
Run Away
Rattled
3.6 m (11′10″)
39.2 kg (86.4 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Dudunsparce
1166
Serene Grace
Run Away
Rattled
3.6 m (11′10″)
39.2 kg (86.4 lbs)
(4,884–5,140 steps)
45 (5.9% with PokéBall, full HP)
Kingambit
1167
Defiant
Supreme Overlord
Pressure
2.0 m (6′07″)
120.0 kg (264.6 lbs)
(4,884–5,140 steps)
25 (3.3% with PokéBall, full HP)
Great Tusk
1168
Protosynthesis
Protosynthesis
Protosynthesis
2.2 m (7′03″)
320.0 kg (705.5 lbs)
(12,594–12,850 steps)
30 (3.9% with PokéBall, full HP)
Scream Tail
1169
Protosynthesis
Protosynthesis
Protosynthesis
1.2 m (3′11″)
8.0 kg (17.6 lbs)
(12,594–12,850 steps)
50 (6.5% with PokéBall, full HP)
Brute Bonnet
1170
Protosynthesis
Protosynthesis
Protosynthesis
1.2 m (3′11″)
21.0 kg (46.3 lbs)
(12,594–12,850 steps)
50 (6.5% with PokéBall, full HP)
Flutter Mane
1171
Protosynthesis
Protosynthesis
Protosynthesis
1.4 m (4′07″)
4.0 kg (8.8 lbs)
(12,594–12,850 steps)
30 (3.9% with PokéBall, full HP)
Slither Wing
1172
Protosynthesis
Protosynthesis
Protosynthesis
3.2 m (10′06″)
92.0 kg (202.8 lbs)
(12,594–12,850 steps)
30 (3.9% with PokéBall, full HP)
Sandy Shocks
1173
Protosynthesis
Protosynthesis
Protosynthesis
2.3 m (7′07″)
60.0 kg (132.3 lbs)
(12,594–12,850 steps)
30 (3.9% with PokéBall, full HP)
Iron Treads
1174
Quark Drive
Quark Drive
Quark Drive
0.9 m (2′11″)
240.0 kg (529.1 lbs)
(12,594–12,850 steps)
30 (3.9% with PokéBall, full HP)
Iron Bundle
1175
Quark Drive
Quark Drive
Quark Drive
0.6 m (2′00″)
11.0 kg (24.3 lbs)
(12,594–12,850 steps)
50 (6.5% with PokéBall, full HP)
Iron Hands
1176
Quark Drive
Quark Drive
Quark Drive
1.8 m (5′11″)
380.7 kg (839.3 lbs)
(12,594–12,850 steps)
50 (6.5% with PokéBall, full HP)
Iron Jugulis
1177
Quark Drive
Quark Drive
Quark Drive
1.3 m (4′03″)
111.0 kg (244.7 lbs)
(12,594–12,850 steps)
30 (3.9% with PokéBall, full HP)
Iron Moth
1178
Quark Drive
Quark Drive
Quark Drive
1.2 m (3′11″)
36.0 kg (79.4 lbs)
(12,594–12,850 steps)
30 (3.9% with PokéBall, full HP)
Iron Thorns
1179
Quark Drive
Quark Drive
Quark Drive
1.6 m (5′03″)
303.0 kg (668.0 lbs)
(12,594–12,850 steps)
30 (3.9% with PokéBall, full HP)
Frigibax
1180
Thermal Exchange
Thermal Exchange
Ice Body
0.5 m (1′08″)
17.0 kg (37.5 lbs)
(10,024–10,280 steps)
45 (5.9% with PokéBall, full HP)
Arctibax
1181
Thermal Exchange
Thermal Exchange
Ice Body
0.8 m (2′07″)
30.0 kg (66.1 lbs)
(10,024–10,280 steps)
25 (3.3% with PokéBall, full HP)
Baxcalibur
1182
Thermal Exchange
Thermal Exchange
Ice Body
2.1 m (6′11″)
210.0 kg (463.0 lbs)
(10,024–10,280 steps)
10 (1.3% with PokéBall, full HP)
Gimmighoul
1183
Rattled
Rattled
Rattled
0.3 m (1′00″)
5.0 kg (11.0 lbs)
(12,594–12,850 steps)
45 (5.9% with PokéBall, full HP)
Gimmighoul
1184
Rattled
Rattled
Rattled
0.3 m (1′00″)
5.0 kg (11.0 lbs)
(12,594–12,850 steps)
45 (5.9% with PokéBall, full HP)
Gholdengo
1185
Good as Gold
Good as Gold
Good as Gold
1.2 m (3′11″)
30.0 kg (66.1 lbs)
(12,594–12,850 steps)
45 (5.9% with PokéBall, full HP)
Wo-Chien
1186
Tablets of Ruin
Tablets of Ruin
Tablets of Ruin
1.5 m (4′11″)
74.2 kg (163.6 lbs)
(12,594–12,850 steps)
6 (0.8% with PokéBall, full HP)
Chien-Pao
1187
Sword of Ruin
Sword of Ruin
Sword of Ruin
1.9 m (6′03″)
152.2 kg (335.5 lbs)
(12,594–12,850 steps)
6 (0.8% with PokéBall, full HP)
Ting-Lu
1188
Vessel of Ruin
Vessel of Ruin
Vessel of Ruin
2.7 m (8′10″)
699.7 kg (1542.6 lbs)
(12,594–12,850 steps)
6 (0.8% with PokéBall, full HP)
Chi-Yu
1189
Beads of Ruin
Beads of Ruin
Beads of Ruin
0.4 m (1′04″)
4.9 kg (10.8 lbs)
(12,594–12,850 steps)
6 (0.8% with PokéBall, full HP)
Roaring Moon
1190
Protosynthesis
Protosynthesis
Protosynthesis
2.0 m (6′07″)
380.0 kg (837.8 lbs)
(12,594–12,850 steps)
10 (1.3% with PokéBall, full HP)
Iron Valiant
1191
Quark Drive
Quark Drive
Quark Drive
1.4 m (4′07″)
35.0 kg (77.2 lbs)
(12,594–12,850 steps)
10 (1.3% with PokéBall, full HP)
Koraidon
1192
Orichalcum Pulse
Orichalcum Pulse
Orichalcum Pulse
2.5 m (8′02″)
303.0 kg (668.0 lbs)
(12,594–12,850 steps)
3 (0.4% with PokéBall, full HP)
Miraidon
1193
Hadron Engine
Hadron Engine
Hadron Engine
3.5 m (11′06″)
240.0 kg (529.1 lbs)
(12,594–12,850 steps)
3 (0.4% with PokéBall, full HP)
Walking Wake
1194
Protosynthesis
Protosynthesis
Protosynthesis
3.5 m (11′06″)
280.0 kg (617.3 lbs)
5 (0.7% with PokéBall, full HP)
Iron Leaves
1195
Quark Drive
Quark Drive
Quark Drive
1.5 m (4′11″)
125.0 kg (275.6 lbs)
5 (0.7% with PokéBall, full HP)
Dipplin
1196
Supersweet Syrup
Gluttony
Sticky Hold
0.4 m (1′04″)
4.4 kg (9.7 lbs)
45 (5.9% with PokéBall, full HP)
Poltchageist
1197
Hospitality
Hospitality
Heatproof
0.1 m (0′04″)
1.1 kg (2.4 lbs)
120 (15.7% with PokéBall, full HP)
Sinistcha
1198
Hospitality
Hospitality
Heatproof
0.2 m (0′08″)
2.2 kg (4.9 lbs)
60 (7.8% with PokéBall, full HP)
Okidogi
1199
Toxic Chain
Toxic Chain
Guard Dog
1.8 m (5′11″)
92.0 kg (202.8 lbs)
3 (0.4% with PokéBall, full HP)
Munkidori
1200
Toxic Chain
Toxic Chain
Frisk
1.0 m (3′03″)
12.2 kg (26.9 lbs)
3 (0.4% with PokéBall, full HP)
Fezandipiti
1201
Toxic Chain
Toxic Chain
Technician
1.4 m (4′07″)
30.1 kg (66.4 lbs)
3 (0.4% with PokéBall, full HP)
Ogerpon
1202
Defiant
Defiant
Embody Aspect
1.2 m (3′11″)
39.8 kg (87.7 lbs)
5 (0.7% with PokéBall, full HP)
Ogerpon
1203
Defiant
Defiant
Embody Aspect
1.2 m (3′11″)
39.8 kg (87.7 lbs)
5 (0.7% with PokéBall, full HP)
Ogerpon
1204
Defiant
Defiant
Embody Aspect
1.2 m (3′11″)
39.8 kg (87.7 lbs)
5 (0.7% with PokéBall, full HP)
Ogerpon
1205
Defiant
Defiant
Embody Aspect
1.2 m (3′11″)
39.8 kg (87.7 lbs)
5 (0.7% with PokéBall, full HP)
Archaludon
1206
Stamina
Sturdy
Stalwart
2.0 m (6′07″)
60.0 kg (132.3 lbs)
10 (1.3% with PokéBall, full HP)
Hydrapple
1207
Supersweet Syrup
Regenerator
Sticky Hold
1.8 m (5′11″)
93.0 kg (205.0 lbs)
10 (1.3% with PokéBall, full HP)
Gouging Fire
1208
Protosynthesis
Protosynthesis
Protosynthesis
3.5 m (11′06″)
590.0 kg (1300.7 lbs)
10 (1.3% with PokéBall, full HP)
Raging Bolt
1209
Protosynthesis
Protosynthesis
Protosynthesis
5.2 m (17′01″)
480.0 kg (1058.2 lbs)
10 (1.3% with PokéBall, full HP)
Iron Boulder
1210
Quark Drive
Quark Drive
Quark Drive
1.5 m (4′11″)
162.5 kg (358.3 lbs)
10 (1.3% with PokéBall, full HP)
Iron Crown
1211
Quark Drive
Quark Drive
Quark Drive
1.6 m (5′03″)
156.0 kg (343.9 lbs)
10 (1.3% with PokéBall, full HP)
Terapagos
1212
Tera Shift
Tera Shift
Tera Shift
0.2 m (0′08″)
6.5 kg (14.3 lbs)
255 (33.3% with PokéBall, full HP)
Terapagos
1213
Tera Shift
Tera Shift
Tera Shift
0.2 m (0′08″)
6.5 kg (14.3 lbs)
255 (33.3% with PokéBall, full HP)
Terapagos
1214
Tera Shift
Tera Shift
Tera Shift
0.2 m (0′08″)
6.5 kg (14.3 lbs)
255 (33.3% with PokéBall, full HP)
Pecharunt
1215
Poison Puppeteer
Poison Puppeteer
Poison Puppeteer
0.3 m (1′00″)
0.3 kg (0.7 lbs)
3 (0.4% with PokéBall, full HP)

In [144]:
# Convertimos la lista en lista de listas para mantener el formato del DF original
conteo = -1
listed_ab =[]
for i in abilities:
    if type(i) != int:
        listed_ab[conteo].append(i)
    else:
        listed_ab.append([])
        conteo +=1
        
# Check de lens
print(len(nombre))
print(len(listed_ab))
print(len(altura))
print(len(capture))
print(len(egg_step))
print(len(peso))

146
146
146
146
124
146

In [145]:
# Transformarmos los datos para mantener formato
altura = [i.split(' ')[0] for i in altura] 
peso = [i.split(' ')[0] for i in peso]
capture = [i.split(' ')[0] for i in capture]  
egg_step = [i[1:6] for i in egg_step]

In [146]:
# Replace de coma por punto
egg_step_2= [i.replace(',','.') for i in egg_step]

egg_step_2

['30.58',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '3.599',
 '3.599',
 '3.599',
 '3.599',
 '3.599',
 '4.884',
 '4.884',
 '3.599',
 '3.599',
 '3.599',
 '2.314',
 '2.314',
 '2.314',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '3.599',
 '3.599',
 '3.599',
 '3.599',
 '4.884',
 '4.884',
 '4.884',
 '8.739',
 '8.739',
 '8.739',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '8.739',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '8.739',
 '10.02',
 '10.02',
 '10.02',
 '4.884',
 '4.884',
 '7.454',
 '8.739',
 '7.454',
 '7.454',
 '4.884',
 '4.884',
 '4.884',
 '6.169',
 '6.169',
 '4.884',
 '10.02',
 '8.739',
 '8.739',
 '8.739',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '4.884',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '10.02',
 '10.02',
 '10.02',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59',
 '12.59']

In [147]:
# Llenamos para tener el mismo len
for i in range(22):
    egg_step_2.append(None)
len(egg_step_2)

146

In [169]:
# COMO CONVIERTO LO SCRAPEADO EN LISTA DE LISTAS PARA QUE TENGAN MISMO LENGHT?
sc = {"Pokedex":numero,"Name":nombre,"Ability":listed_ab,"Height":altura,"Weight":peso,"Base_egg_step":egg_step_2,"Capture":capture}
df = pd.DataFrame(sc)
df.head()

# Guardamos a csv
df.to_csv('9_gen_df.csv')
gen_df = pd.read_csv('9_gen_df.csv')

In [170]:
# ELiminamos las columnas no deseadas
gen_df.drop(columns='Unnamed: 0',inplace=True)
pokemon_casi.drop(columns='Unnamed: 0',inplace=True)
# Cambiamos types
gen_df["Weight"] = gen_df["Weight"].astype(float)
gen_df["Base_egg_step"] = gen_df["Base_egg_step"].astype(float)
gen_df["Height"] = gen_df["Height"].astype(int)

In [171]:
pokemon_casi.head()

,Pokedex_number,Name,Evolution,Base_type,Secondary_type,Abilities,Generation,Legendary,Attack,Defense,Hp,Sp_attack,Sp_defense,Speed,Height_m,Weight_kg,Against_bug,Against_dark,Against_dragon,Against_electric,Against_fairy,Against_fight,Against_fire,Against_flying,Against_ghost,Against_grass,Against_ground,Against_ice,Against_normal,Against_poison,Against_psychic,Against_rock,Against_steel,Against_water,Base_egg_steps,Base_happiness,Base_total,Capture_rate,Experience_growth
0,1,Bulbasaur,Ivysaur,Grass,Poison,"['Overgrow', 'Chlorophyll']",1.0,0.0,49,49,45,65,65,45,0.7,6.9,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120.0,70.0,318,45,1059860.0
1,2,Ivysaur,Venusaur,Grass,Poison,"['Overgrow', 'Chlorophyll']",1.0,0.0,62,63,60,80,80,60,1.0,13.0,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120.0,70.0,405,45,1059860.0
2,3,Venusaur,Unknown,Grass,Poison,"['Overgrow', 'Chlorophyll']",1.0,0.0,100,123,80,122,120,80,2.0,100.0,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120.0,70.0,625,45,1059860.0
3,4,Charmander,Charmeleon,Fire,Nan,"['Blaze', 'Solar Power']",1.0,0.0,52,43,39,60,50,65,0.6,8.5,0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0,5120.0,70.0,309,45,1059860.0
4,5,Charmeleon,Charizard,Fire,Nan,"['Blaze', 'Solar Power']",1.0,0.0,64,58,58,80,65,80,1.1,19.0,0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0,5120.0,70.0,405,45,1059860.0

In [172]:
# Hacemos un merge por nombre para poder añadir el resto de features
pokemon_casi = pokemon_casi.merge(gen_df, left_on='Name', right_on='Name',how='left')

#Añadimos las features de los pokemons que hemos traido con el merge a nuestro df
gen9_stats = gen_df["Name"].to_list()
pokemon_casi["Abilities"] = pokemon_casi.apply(lambda x: x["Ability"] if x["Name"] in gen9_stats else x["Abilities"], axis=1)
pokemon_casi["Height_m"] = pokemon_casi.apply(lambda x: x["Height"] if x["Name"] in gen9_stats else x["Height_m"], axis=1)
pokemon_casi["Weight_kg"] = pokemon_casi.apply(lambda x: x["Weight"] if x["Name"] in gen9_stats else x["Weight_kg"], axis=1)
pokemon_casi["Base_egg_steps"] = pokemon_casi.apply(lambda x: x["Base_egg_step"] if x["Name"] in gen9_stats else x["Base_egg_steps"], axis=1)
pokemon_casi["Capture_rate"] = pokemon_casi.apply(lambda x: x["Capture"] if x["Name"] in gen9_stats else x["Capture_rate"], axis=1)

pokemon_casi

,Pokedex_number,Name,Evolution,Base_type,Secondary_type,Abilities,Generation,Legendary,Attack,Defense,Hp,Sp_attack,Sp_defense,Speed,Height_m,Weight_kg,Against_bug,Against_dark,Against_dragon,Against_electric,Against_fairy,Against_fight,Against_fire,Against_flying,Against_ghost,Against_grass,Against_ground,Against_ice,Against_normal,Against_poison,Against_psychic,Against_rock,Against_steel,Against_water,Base_egg_steps,Base_happiness,Base_total,Capture_rate,Experience_growth,Pokedex,Ability,Height,Weight,Base_egg_step,Capture
0,1,Bulbasaur,Ivysaur,Grass,Poison,"['Overgrow', 'Chlorophyll']",1.0,0.0,49,49,45,65,65,45,0.7,6.9,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120.0,70.0,318,45,1059860.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Ivysaur,Venusaur,Grass,Poison,"['Overgrow', 'Chlorophyll']",1.0,0.0,62,63,60,80,80,60,1.0,13.0,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120.0,70.0,405,45,1059860.0,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Venusaur,Unknown,Grass,Poison,"['Overgrow', 'Chlorophyll']",1.0,0.0,100,123,80,122,120,80,2.0,100.0,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120.0,70.0,625,45,1059860.0,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Charmander,Charmeleon,Fire,Nan,"['Blaze', 'Solar Power']",1.0,0.0,52,43,39,60,50,65,0.6,8.5,0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0,5120.0,70.0,309,45,1059860.0,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Charmeleon,Charizard,Fire,Nan,"['Blaze', 'Solar Power']",1.0,0.0,64,58,58,80,65,80,1.1,19.0,0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0,5120.0,70.0,405,45,1059860.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057,1023,Iron Crown,Unknown,Steel,Psychic,"['Quark Drive', 'Quark Drive', 'Quark Drive']",NaN,NaN,72,100,90,122,108,98,1.0,156.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,590,10.0,NaN,1211.0,"['Quark Drive', 'Quark Drive', 'Quark Drive']",1.0,156.0,NaN,10.0
1058,1024,Terapagos,No hay,Normal,NaN,"['Tera Shift', 'Tera Shift', 'Tera Shift']",NaN,NaN,65,85,90,65,85,60,0.0,6.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450,255.0,NaN,1212.0,"['Tera Shift', 'Tera Shift', 'Tera Shift']",0.0,6.5,NaN,255.0
1059,1024,Terapagos,No hay,Normal,NaN,"['Tera Shift', 'Tera Shift', 'Tera Shift']",NaN,NaN,65,85,90,65,85,60,0.0,6.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450,255.0,NaN,1213.0,"['Tera Shift', 'Tera Shift', 'Tera Shift']",0.0,6.5,NaN,255.0
1060,1024,Terapagos,No hay,Normal,NaN,"['Tera Shift', 'Tera Shift', 'Tera Shift']",NaN,NaN,65,85,90,65,85,60,0.0,6.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450,255.0,NaN,1214.0,"['Tera Shift', 'Tera Shift', 'Tera Shift']",0.0,6.5,NaN,255.0
1061,1025,Pecharunt,No hay,Poison,Ghost,"['Poison Puppeteer', 'Poison Puppeteer', 'Pois...",NaN,NaN,88,160,88,88,88,88,0.0,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600,3.0,NaN,1215.0,"['Poison Puppeteer', 'Poison Puppeteer', 'Pois...",0.0,0.3,NaN,3.0

In [ ]:
# Dropeamos las columnas extra que nos ha traido el merge

pokemon_casi.drop(columns=["Pokedex","Ability","Height","Weight","Base_egg_step","Capture"],inplace=True)
pokemon_casi.tail()

In [177]:
# Fillna de secondary type
pokemon_casi["Secondary_type"].fillna('No more types',inplace= True)
# Replace de los Nan por el valor que toca
pokemon_casi["Secondary_type"] = pokemon_casi["Secondary_type"].apply(lambda x: 'No more types' if 'Nan' in x else x)

In [180]:
# Rellenamos campos que van faltando
pokemon_casi["Generation"].fillna(9.0,inplace=True)

In [ ]:
# Mostramos los duplicados para poder corregir
pokemon_casi[pokemon_casi.duplicated(keep=False)]

,Pokedex_number,Name,Evolution,Base_type,Secondary_type,Abilities,Generation,Legendary,Attack,Defense,Hp,Sp_attack,Sp_defense,Speed,Height_m,Weight_kg,Against_bug,Against_dark,Against_dragon,Against_electric,Against_fairy,Against_fight,Against_fire,Against_flying,Against_ghost,Against_grass,Against_ground,Against_ice,Against_normal,Against_poison,Against_psychic,Against_rock,Against_steel,Against_water,Base_egg_steps,Base_happiness,Base_total,Capture_rate,Experience_growth
919,901,Ursaluna,Unknown,Nan,No more types,"['Guts', 'Bulletproof', 'Unnerve']",9.0,NaN,140,105,130,45,80,50,2.0,290.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.884,NaN,550,20.0,NaN
920,901,Ursaluna,Unknown,Nan,No more types,"['Guts', 'Bulletproof', 'Unnerve']",9.0,NaN,140,105,130,45,80,50,2.0,290.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.884,NaN,550,20.0,NaN
921,902,Basculegion,Unknown,Nan,No more types,"['Swift Swim', 'Adaptability', 'Mold Breaker']",9.0,NaN,112,65,120,80,75,78,3.0,110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.884,NaN,530,45.0,NaN
922,902,Basculegion,Unknown,Nan,No more types,"['Swift Swim', 'Adaptability', 'Mold Breaker']",9.0,NaN,112,65,120,80,75,78,3.0,110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.884,NaN,530,45.0,NaN
925,905,Enamorus,No hay,Nan,No more types,"['Cute Charm', 'Cute Charm', 'Contrary']",9.0,NaN,115,70,74,135,80,106,1.0,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.884,NaN,580,3.0,NaN
926,905,Enamorus,No hay,Nan,No more types,"['Cute Charm', 'Cute Charm', 'Contrary']",9.0,NaN,115,70,74,135,80,106,1.0,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.884,NaN,580,3.0,NaN
937,916,Oinkologne,Unknown,Normal,No more types,"['Lingering Aroma', 'Gluttony', 'Thick Fat']",9.0,NaN,100,75,110,59,80,65,1.0,120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.599,NaN,489,100.0,NaN
938,916,Oinkologne,Unknown,Normal,No more types,"['Lingering Aroma', 'Gluttony', 'Thick Fat']",9.0,NaN,100,75,110,59,80,65,1.0,120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.599,NaN,489,100.0,NaN
947,925,Maushold,Unknown,Normal,No more types,"['Friend Guard', 'Cheek Pouch', 'Technician']",9.0,NaN,75,70,74,65,75,111,0.0,2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314,NaN,470,75.0,NaN
948,925,Maushold,Unknown,Normal,No more types,"['Friend Guard', 'Cheek Pouch', 'Technician']",9.0,NaN,75,70,74,65,75,111,0.0,2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.314,NaN,470,75.0,NaN
954,931,Squawkabilly,No hay,Normal,Flying,"['Intimidate', 'Hustle', 'Guts']",9.0,NaN,96,51,82,45,51,92,0.0,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.599,NaN,417,190.0,NaN
955,931,Squawkabilly,No hay,Normal,Flying,"['Intimidate', 'Hustle', 'Guts']",9.0,NaN,96,51,82,45,51,92,0.0,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.599,NaN,417,190.0,NaN
956,931,Squawkabilly,No hay,Normal,Flying,"['Intimidate', 'Hustle', 'Guts']",9.0,NaN,96,51,82,45,51,92,0.0,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.599,NaN,417,190.0,NaN
957,931,Squawkabilly,No hay,Normal,Flying,"['Intimidate', 'Hustle', 'Guts']",9.0,NaN,96,51,82,45,51,92,0.0,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.599,NaN,417,190.0,NaN
990,964,Palafin,Unknown,Water,No more types,"['Zero to Hero', 'Zero to Hero', 'Zero to Hero']",9.0,NaN,70,72,100,53,62,100,1.0,60.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.020,NaN,457,45.0,NaN
991,964,Palafin,Unknown,Water,No more types,"['Zero to Hero', 'Zero to Hero', 'Zero to Hero']",9.0,NaN,70,72,100,53,62,100,1.0,60.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.020,NaN,457,45.0,NaN
1005,978,Tatsugiri,No hay,Dragon,Water,"['Commander', 'Commander', 'Storm Drain']",9.0,NaN,50,60,68,120,95,82,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.739,NaN,475,100.0,NaN
1006,978,Tatsugiri,No hay,Dragon,Water,"['Commander', 'Commander', 'Storm Drain']",9.0,NaN,50,60,68,120,95,82,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.739,NaN,475,100.0,NaN
1007,978,Tatsugiri,No hay,Dragon,Water,"['Commander', 'Commander', 'Storm Drain']",9.0,NaN,50,60,68,120,95,82,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.739,NaN,475,100.0,NaN
1011,982,Dudunsparce,Unknown,Normal,No more types,"['Serene Grace', 'Run Away', 'Rattled']",9.0,NaN,100,80,125,85,75,55,3.0,39.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.884,NaN,520,45.0,NaN
1012,982,Dudunsparce,Unknown,Normal,No more types,"['Serene Grace', 'Run Away', 'Rattled']",9.0,NaN,100,80,125,85,75,55,3.0,39.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.884,NaN,520,45.0,NaN
1029,999,Gimmighoul,Gholdengo,Ghost,No more types,"['Rattled', 'Rattled', 'Rattled']",9.0,NaN,30,70,45,75,70,10,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.590,NaN,300,45.0,NaN
1030,999,Gimmighoul,Gholdengo,Ghost,No more types,"['Rattled', 'Rattled', 'Rattled']",9.0,NaN,30,70,45,75,70,10,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.590,NaN,300,45.0,NaN
1048,1017,Ogerpon,No hay,Grass,No more types,"['Defiant', 'Defiant', 'Embody Aspect']",9.0,NaN,120,84,80,60,96,110,1.0,39.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,550,5.0,NaN
1049,1017,Ogerpon,No hay,Grass,No more types,"['Defiant', 'Defiant', 'Embody Aspect']",9.0,NaN,120,84,80,60,96,110,1.0,39.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,550,5.0,NaN
1050,1017,Ogerpon,No hay,Grass,No more types,"['Defiant', 'Defiant', 'Embody Aspect']",9.0,NaN,120,84,80,60,96,110,1.0,39.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,550,5.0,NaN
1051,1017,Ogerpon,No hay,Grass,No more types,"['Defiant', 'Defiant', 'Embody Aspect']",9.0,NaN,120,84,80,60,96,110,1.0,39.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,550,5.0,NaN
1058,1024,Terapagos,No hay,Normal,No more types,"['Tera Shift', 'Tera Shift', 'Tera Shift']",9.0,NaN,65,85,90,65,85,60,0.0,6.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450,255.0,NaN
1059,1024,Terapagos,No hay,Normal,No more types,"['Tera Shift', 'Tera Shift', 'Tera Shift']",9.0,NaN,65,85,90,65,85,60,0.0,6.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450,255.0,NaN
1060,1024,Terapagos,No hay,Normal,No more types,"['Tera Shift', 'Tera Shift', 'Tera Shift']",9.0,NaN,65,85,90,65,85,60,0.0,6.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450,255.0,NaN

In [ ]:
# Corregimos legendarios que faltaban

legend = {488:1,
          792:0,
          793:0,
          794:0,
          795:0,
          796:0,
          797:0,
          798:0,
          771:1,
          772:1,
          919:1,
          925:1,
          926:1,
          1032:1,
          1033:1,
          1034:1,
          1035:1,
          1038:1,
          1039:1,
          1045:1,
          1046:1,
          1047:1,
          1048:1,
          1049:1,
          1050:1,
          1051:1,
          1058:1,
          1059:1,
          1060:1}
pokemon_casi["Legendary"].update(pd.Series(legend))

# Adaptamos para no tener unknows o nulls en las Evoluciones

pokemon_casi["Evolution"].replace({"Unknown":"Final Form",
                              "No hay":"Final Form"}, inplace=True)

# Rellenamos con la media en Wheight i Height los nulls
pokemon_casi["Height_m"] = pokemon_casi["Height_m"].fillna(pokemon_casi["Height_m"].mean())
pokemon_casi["Weight_kg"] = pokemon_casi["Weight_kg"].fillna(pokemon_casi["Weight_kg"].mean())

# Corregimos algunos nombres

names = {920:'Ursalana Bloodmoon',
         921:'Basculegion Male',
         922:'Basculegion Female',
         925:,
         926:,
         937:,
         938:,
         947:,
         948:,
         954:,
         955:,
         956:,
         957:,
         990:,
         991:,
         1005:,
         1006:,
         1007:,
         1011:,
         1012:,
         1029:,
         1030:,
         1048:,
         1049:,
         1050:,
         1051:,
         1058:,
         1059:,
         1060:
         }

pokemon_casi["Name"].update(pd.Series(names))

,Pokedex_number,Name,Evolution,Base_type,Secondary_type,Abilities,Generation,Legendary,Attack,Defense,Hp,Sp_attack,Sp_defense,Speed,Height_m,Weight_kg,Against_bug,Against_dark,Against_dragon,Against_electric,Against_fairy,Against_fight,Against_fire,Against_flying,Against_ghost,Against_grass,Against_ground,Against_ice,Against_normal,Against_poison,Against_psychic,Against_rock,Against_steel,Against_water,Base_egg_steps,Base_happiness,Base_total,Capture_rate,Experience_growth
0,1,Bulbasaur,Ivysaur,Grass,Poison,"['Overgrow', 'Chlorophyll']",1.0,0.0,49,49,45,65,65,45,0.7,6.9,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120.0,70.0,318,45,1059860.0
1,2,Ivysaur,Venusaur,Grass,Poison,"['Overgrow', 'Chlorophyll']",1.0,0.0,62,63,60,80,80,60,1.0,13.0,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120.0,70.0,405,45,1059860.0
2,3,Venusaur,Unknown,Grass,Poison,"['Overgrow', 'Chlorophyll']",1.0,0.0,100,123,80,122,120,80,2.0,100.0,1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5,5120.0,70.0,625,45,1059860.0
3,4,Charmander,Charmeleon,Fire,No more types,"['Blaze', 'Solar Power']",1.0,0.0,52,43,39,60,50,65,0.6,8.5,0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0,5120.0,70.0,309,45,1059860.0
4,5,Charmeleon,Charizard,Fire,No more types,"['Blaze', 'Solar Power']",1.0,0.0,64,58,58,80,65,80,1.1,19.0,0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0,5120.0,70.0,405,45,1059860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057,1023,Iron Crown,Unknown,Steel,Psychic,"['Quark Drive', 'Quark Drive', 'Quark Drive']",9.0,NaN,72,100,90,122,108,98,1.0,156.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,590,10.0,NaN
1058,1024,Terapagos,No hay,Normal,No more types,"['Tera Shift', 'Tera Shift', 'Tera Shift']",9.0,NaN,65,85,90,65,85,60,0.0,6.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450,255.0,NaN
1059,1024,Terapagos,No hay,Normal,No more types,"['Tera Shift', 'Tera Shift', 'Tera Shift']",9.0,NaN,65,85,90,65,85,60,0.0,6.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450,255.0,NaN
1060,1024,Terapagos,No hay,Normal,No more types,"['Tera Shift', 'Tera Shift', 'Tera Shift']",9.0,NaN,65,85,90,65,85,60,0.0,6.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450,255.0,NaN
1061,1025,Pecharunt,No hay,Poison,Ghost,"['Poison Puppeteer', 'Poison Puppeteer', 'Pois...",9.0,NaN,88,160,88,88,88,88,0.0,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600,3.0,NaN

In [127]:
# Juntamos los types en una columna

pokemon_casi["Combination"] = pokemon_casi["Base_type"] + ', ' + pokemon_casi["Secondary_type"]
len(set(pokemon_casi["Combination"]))

213

In [128]:
# No NAN DF

pokemon_no_na = pokemon_casi[~pokemon_casi["Against_bug"].isna()]

In [87]:
# Cogemos la media por against
all_types = set(pokemon_no_na["Combination"])
# Creamos un diccionario vacio para ir añadiendo las medias de against
defense_mapping = {}


for comb in all_types:
    # Split for types
    base, secondary = comb.split(', ')
    # Mean for each against type in the DF
    against_bug_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_bug"].mean()
    against_dark_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_dark"].mean()
    against_fire_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_fire"].mean()
    against_electric_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_electric"].mean()
    against_dragon_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_dragon"].mean()
    against_fairy_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_fairy"].mean()
    against_fight_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_fight"].mean()
    against_fly_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_flying"].mean()
    against_ghost_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_ghost"].mean()
    against_grass_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_grass"].mean()
    against_ground_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_ground"].mean()
    against_ice_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_ice"].mean()
    against_normal_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_normal"].mean()
    against_poison_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_poison"].mean()
    against_psy_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_psychic"].mean()
    against_rock_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_rock"].mean()
    against_steel_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_steel"].mean()
    against_water_mean = pokemon_no_na[(pokemon_no_na["Base_type"] == base) & (pokemon_no_na["Secondary_type"] == secondary)]["Against_water"].mean()

    # Append it to the dictionary
    defense_mapping[comb]["bug"] = against_bug_mean
    defense_mapping[comb]["dark"] = against_dark_mean
    defense_mapping[comb]["fire"] = against_fire_mean
    defense_mapping[comb]["electric"] = against_electric_mean
    defense_mapping[comb]["dragon"] = against_dragon_mean
    defense_mapping[comb]["fairy"] = against_fairy_mean
    defense_mapping[comb]["fight"] = against_fight_mean
    defense_mapping[comb]["flying"] = against_fly_mean
    defense_mapping[comb]["ghost"] = against_ghost_mean
    defense_mapping[comb]["grass"] = against_grass_mean
    defense_mapping[comb]["ground"] = against_ground_mean
    defense_mapping[comb]["ice"] = against_ice_mean
    defense_mapping[comb]["normal"] = against_normal_mean
    defense_mapping[comb]["poison"] = against_poison_mean
    defense_mapping[comb]["psychic"] = against_psy_mean
    defense_mapping[comb]["rock"] = against_rock_mean
    defense_mapping[comb]["steel"] = against_steel_mean
    defense_mapping[comb]["water"] = against_water_mean
    
print(defense_mapping)

KeyError: 'Ground, Fire'

In [133]:
against_bug_mean

1.0

In [ ]:
pokemon_casi[(pokemon_casi["Base_type"] == 'Ground') & (pokemon_casi["Secondary_type"] == 'Fire')]

,Pokedex_number,Name,Evolution,Base_type,Secondary_type,Abilities,Generation,Legendary,Attack,Defense,Hp,Sp_attack,Sp_defense,Speed,Height_m,Weight_kg,Against_bug,Against_dark,Against_dragon,Against_electric,Against_fairy,Against_fight,Against_fire,Against_flying,Against_ghost,Against_grass,Against_ground,Against_ice,Against_normal,Against_poison,Against_psychic,Against_rock,Against_steel,Against_water,Base_egg_steps,Base_happiness,Base_total,Capture_rate,Experience_growth,Combination
104,105,Marowak,Unknown,Ground,Fire,"['Rock Head', 'Lightningrod', 'Battle Armor', ...",1.0,0.0,80,110,60,50,80,45,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,0.5,1.0,0.5,1.0,2.0,5120.0,70.0,425,75,1000000.0,"Ground, Fire"

In [ ]:
# Creamos una nueva columna con el numero de habilidades que tiene cada pokemon para pasarlo al modelo
def count_abilities(x):
    return len(x.split(","))

pokemon_casi['Number_of_Abilities'] = pokemon_casi['Abilities'].apply(count_abilities)

pokemon_casi['Number_of_Abilities']

In [ ]:
pokemon_casi.tail()

,Pokedex_number,Name,Evolution,Base_type,Secondary_type,Abilities,Generation,Legendary,Attack,Defense,Hp,Sp_attack,Sp_defense,Speed,Height_m,Weight_kg,Against_bug,Against_dark,Against_dragon,Against_electric,Against_fairy,Against_fight,Against_fire,Against_flying,Against_ghost,Against_grass,Against_ground,Against_ice,Against_normal,Against_poison,Against_psychic,Against_rock,Against_steel,Against_water,Base_egg_steps,Base_happiness,Base_total,Capture_rate,Experience_growth
1039,1021,Raging Bolt,Final Form,Electric,Dragon,NaN,9.0,0.0,73,91,125,137,89,75,1.196205,64.576563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,590,NaN,NaN
1040,1022,Iron Boulder,Final Form,Rock,Psychic,NaN,9.0,0.0,120,80,90,68,108,124,1.196205,64.576563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,590,NaN,NaN
1041,1023,Iron Crown,Final Form,Steel,Psychic,NaN,9.0,0.0,72,100,90,122,108,98,1.196205,64.576563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,590,NaN,NaN
1042,1024,Terapagos,Final Form,Normal,No more types,NaN,9.0,1.0,65,85,90,65,85,60,1.196205,64.576563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450,NaN,NaN
1043,1025,Pecharunt,Final Form,Poison,Ghost,NaN,9.0,1.0,88,160,88,88,88,88,1.196205,64.576563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600,NaN,NaN

In [ ]:
# OBJETIVOS

# ULTIMATE POKEDEX CON STREAMLIT
# Primera pestaña introduccion

# MAPEO DE DONDE SE ENCUENTRAN LOS POKEMONS (GEOJSON MAPA POKEMON?/MAPA REAL?) PARA VER DONDE CAPTURARLOS
# MONTAR TU PROPIO EQUIPO Y PODER HACER PREDICTOR DE BATALLAS
# CLASIFICADOR DE POKEMON SEGUN FEATURES? Y RECOMENDAR, TAMBIEN LINKEARLO CON CHATGTP Y PODER CREAR UNA IMAGEN(TIPO, LEGENDARIO, GENERACION, ESTADISTICAS ETC..)


# CONSTRUIR UN POKEMON A PARTIR DE IMAGENES USANDO ALGORITMO DE CLASIFICACION? (DEMASIADO LOCO CREO) - HACER PESTAÑA CON QUIZZ
# ANALISIS DESCRIPTIVO DE LOS DATOS

# AÑADIR LLM PARA QUE STREAMLIT SEA INTERACTIVO? SI SOBRA TIEMPO (NO ES UNA PRIORIDAD)
# CREAR UN POKEMON VIA CHATGPT